INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.16, 17
("v.-000-001", "ver",       "ver.png",      "v."),
("v.-000-002", "querer",    "querer.png",   "v."),
("v.-000-003", "escuchar",  "escuchar.png", "v."),
("v.-000-004", "agarrar",   "agarrar.png",  "v."),
("v.-000-005", "hacer",     "hacer.png",    "v."),
("v.-000-006", "comer",     "comer.png",    "v."),
("v.-000-007", "beber",     "beber.png",    "v."),
("v.-000-008", "amar",      "amar.png",     "v."),
("v.-000-009", "dormir",   "dormir.png",    "v."),
("v.-000-010", "caminar",  "caminar.png",   "v."),
("v.-000-011", "bailar",   "bailar.png",    "v."),
("v.-000-012", "llorar",   "llorar.png",    "v."),
("v.-000-013", "reír",     "reír.png",      "v."),
("v.-000-014", "trabajar", "trabajar.png",  "v."),
("v.-000-015", "escribir", "escribir.png",  "v."),
("v.-000-016", "contar",   "contar.png",    "v."),
("v.-000-017", "cortar",   "cortar.png",    "v."),
("v.-000-018", "barrer",   "barrer.png",    "v."),
("v.-000-019", "decir",    "decir.png",     "v."),
("v.-000-020", "coser",    "coser.png",     "v."),
("v.-000-021", "tener",    "tener.png",     "v."),
("v.-000-022", "vender",   "vender.png",    "v."),
("v.-000-023", "ganar",    "ganar.png",     "v."),
("v.-000-024", "enojar",   "enojar.png",    "v."),
("v.-000-025", "gritar",   "gritar.png",    "v."),
("v.-000-026", "jugar",    "jugar.png",     "v.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.20
("pron.pers.-01", "yo",       "yo.png",       "pron.pers."),
("pron.pers.-02", "tú",       "tú.png",       "pron.pers."),
("pron.pers.-03", "él",       "él.png",       "pron.pers."),
("pron.pers.-04", "nosotros", "nosotros.png", "pron.pers."),
("pron.pers.-05", "ustedes",  "ustedes.png",  "pron.pers."),
("pron.pers.-06", "ellos",    "ellos.png",    "pron.pers.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.22
("pron.dem.-01", "este, esta, esto (objeto)", "este.png",  "pron.dem."),
("pron.dem.-02", "ese, esa, eso (objeto)",    "ese.png",   "pron.dem."),
("pron.dem.-03", "aquel, aquello",            "aquel.png", "pron.dem."),
("pron.dem.-04", "allá",                      "allá.png",  "pron.dem.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES  --pag.23
("pron.indef.-01", "quien",      "yo.png", "pron.indef."),
("pron.indef.-02", "algunos",    "tú.png", "pron.indef."),
("pron.indef.-03", "otro",       "tú.png", "pron.indef."),
("pron.indef.-04", "cualquiera", "él.png", "pron.indef."),
("pron.indef.-05", "nadie",      "él.png", "pron.indef.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES  --pag.24
("pref.prnl.suj.-01", "primera persona del singular", "primera persona del singular.png", "pron.indef."), --pag.24
("pref.prnl.suj.-02", "segunda persona del singular", "segunda persona del singular.png", "pron.indef."),
("pref.prnl.suj.-03", "primera persona del plural",   "primera persona del plural.png",   "pron.indef."),
("pref.prnl.suj.-04", "segunda persona del plural",   "segunda persona del plural.png",   "pron.indef.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES  --pag.24
("pref.prnl.-01", "mi me",          "mi me.png",           "pref.prnl."),
("pref.prnl.-02", "a ti te",        "a ti te.png",         "pref.prnl."),
("pref.prnl.-03", "a él le",        "a él le.png",         "pref.prnl."),
("pref.prnl.-04", "a nosotros nos", "a nosotros nos.png",  "pref.prnl."),
("pref.prnl.-05", "a ustedes les",  "a ustedes les.png",   "pref.prnl."),
("pref.prnl.-06", "a ellos ",       "a ellos .png",        "pref.prnl.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES  --pag.25
("pref.pos.-01", "mío",        "mío.png",        "pref.pos."),
("pref.pos.-02", "tuyo",       "tuyo.png",       "pref.pos."),
("pref.pos.-03", "suyo",       "suyo.png",       "pref.pos."),
("pref.pos.-04", "nuestro" ,   "nuestro.png",    "pref.pos."),
("pref.pos.-05", "de ustedes", "de ustedes.png", "pref.pos."),
("pref.pos.-06", "de ellos",   "de ellos.png",   "pref.pos.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES  --pag.25
("pref.prnl.r-01", "a mí mismo",        "a mí mismo.png",        "pref.prnl.r"),
("pref.prnl.r-02", "a tí mismo",        "a tí mismo.png",        "pref.prnl.r"),
("pref.prnl.r-03", "a él mismo",        "a él mismo.png",        "pref.prnl.r"),
("pref.prnl.r-04", "a nosotros mismos", "a nosotros mismos.png", "pref.prnl.r"),
("pref.prnl.r-05", "a ustedes mismos",  "a ustedes mismos.png",  "pref.prnl.r");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES  --pag.26
("pref.indef.-01", "se refiere a pertenencia de alguien", "se refiere a pertenencia de alguien.png", "pref.indef."),
("pref.indef.-02", "prefijo de acción",                   "prefijo de acción.png",                   "pref.indef.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.26, 27, 28
("adv.-001", "lejos",                           "lejos.png",                           "adv."),
("adv.-002", "cerca",                           "cerca.png",                           "adv."),
("adv.-003", "pasado mañana",                   "pasado mañana.png",                   "adv."),
("adv.-004", "bien",                            "bien.png",                            "adv."),
("adv.-005", "despacio",                        "despacio.png",                        "adv."),
("adv.-006", "siempre",                         "siempre.png",                         "adv."),
("adv.-007", "nunca",                           "nunca.png",                           "adv."),
("adv.-008", "posiblemente",                    "posiblemente.png",                    "adv."),
("adv.-009", "nada",                            "nada.png",                            "adv."),
("adv.-010", "de nada",                         "de nada.png",                         "adv."),
("adv.-011", "donde",                           "donde.png",                           "adv."),
("adv.-012", "aquí",                            "aquí.png",                            "adv."),
("adv.-013", "allá",                            "allá.png",                            "adv."),
("adv.-014", "abajo",                           "abajo.png",                           "adv."),
("adv.-015", "arriba",                          "arriba.png",                          "adv."),
("adv.-016", "ya tardó",                        "ya tardó.png",                        "adv."),
("adv.-017", "aquí",                            "aquí.png",                            "adv."),
("adv.-018", "por acá",                         "por acá.png",                         "adv."),
("adv.-019", "lejos",                           "lejos.png",                           "adv."),
("adv.-020", "cuando",                          "cuando.png",                          "adv."),
("adv.-021", "hoy",                             "hoy.png",                             "adv."),
("adv.-022", "mañana",                          "mañana.png",                          "adv."),
("adv.-023", "ayer",                            "ayer.png",                            "adv."),
("adv.-024", "como",                            "como.png",                            "adv."),
("adv.-025", "así",                             "así.png",                             "adv."),
("adv.-026", "pronto",                          "pronto.png",                          "adv."),
("adv.-027", "duro",                            "duro.png",                            "adv."),
("adv.-028", "fuerte",                          "fuerte.png",                          "adv."),
("adv.-029", "verdadero",                       "verdadero.png",                       "adv."),
("adv.-030", "si",                              "si.png",                              "adv."),
("adv.-031", "también",                         "también.png",                         "adv."),
("adv.-032", "bonito",                          "bonito.png",                          "adv."),
("adv.-033", "correctamente",                   "correctamente.png",                   "adv."),
("adv.-034", "no",                              "no.png",                              "adv."),
("adv.-035", "aun no",                          "aun no.png",                          "adv."),
("adv.-036", "ya no",                           "ya no.png",                           "adv."),
("adv.-037", "nunca",                           "nunca.png",                           "adv."),
("adv.-038", "quién sabe (duda)",               "quién sabe (duda).png",               "adv."),
("adv.-039", "mucho",                           "mucho.png",                           "adv."),
("adv.-030", "poco",                            "poco.png",                            "adv."),
("adv.-040", "nada",                            "nada.png",                            "adv."),
("adv.-041", "muy",                             "muy.png",                             "adv."),
("adv.-042", "tal vez",                         "tal vez.png",                         "adv."),
("adv.-043", "aunque no",                       "aunque no.png",                       "adv."),
("adv.-044", "como es posible",                 "como es posible.png",                 "adv."),
("adv.-045", "y",                               "y.png",                               "adv."),
("adv.-046", "así",                             "así.png",                             "adv."),
("adv.-047", "por qué",                         "por qué.png",                         "adv."),
("adv.-048", "pues, porque",                    "pues, porque.png",                    "adv."),
("adv.-049", "junto a él",                      "junto a él.png",                      "adv."),
("adv.-050", "junto de ellos",                  "junto de ellos.png",                  "adv."),
("adv.-051", "sí (condicionante)",              "sí (condicionante).png",              "adv."),
("adv.-052", "cierto",                          "cierto.png",                          "adv."),
("adv.-053", "sí es cierto (condicionante)",    "sí es cierto (condicionante).png",    "adv."),
("adv.-054", "sí no es cierto (condicionante)", "sí no es cierto (condicionante).png", "adv."),
("adv.-055", "aunque",                          "aunque.png",                          "adv."),
("adv.-056", "eso dicen",                       "eso dicen.png",                       "adv."),
("adv.-057", "delgado",                         "delgado.png",                         "adv."),
("adv.-058", "más",                             "más.png",                             "adv."),
("adv.-059", "gordo",                           "gordo.png",                           "adv."),
("adv.-060", "largo",                           "largo.png",                           "adv."),
("adv.-061", "bajo (lugar)",                    "bajo (lugar).png",                    "adv."),
("adv.-062", "abajo",                           "abajo.png",                           "adv.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.28, 29
("adj.calificat.-001", "bonita",    "bonita.png",    "adj.calificat."),
("adj.calificat.-002", "chica",     "chica.png",     "adj.calificat."),
("adj.calificat.-003", "blanca",    "blanca.png",    "adj.calificat."),
("adj.calificat.-004", "limpia",    "limpia.png",    "adj.calificat."),
("adj.calificat.-005", "bella",     "bella.png",     "adj.calificat."),
("adj.calificat.-006", "redonda",   "redonda.png",   "adj.calificat."),
("adj.calificat.-007", "grande",    "grande.png",    "adj.calificat."),
("adj.calificat.-008", "roja",      "roja.png",      "adj.calificat."),
("adj.calificat.-009", "negro",     "negro.png",     "adj.calificat."),
("adj.calificat.-010", "pequeño",   "pequeño.png",   "adj.calificat."),
("adj.calificat.-011", "bravo",     "bravo.png",     "adj.calificat."),
("adj.calificat.-012", "miedoso",   "miedoso.png",   "adj.calificat."),
("adj.calificat.-013", "enojón",    "enojón.png",    "adj.calificat."),
("adj.calificat.-014", "grueso",    "grueso.png",    "adj.calificat."),
("adj.calificat.-015", "largo",     "largo.png",     "adj.calificat."),
("adj.calificat.-016", "fuerte",    "fuerte.png",    "adj.calificat."),
("adj.calificat.-017", "delgado",   "delgado.png",   "adj.calificat."),
("adj.calificat.-018", "resbaloso", "resbaloso.png", "adj.calificat."),
("adj.calificat.-019", "quebrado",  "quebrado.png",  "adj.calificat."),
("adj.calificat.-020", "hervido",   "hervido.png",   "adj.calificat."),
("adj.calificat.-021", "lavado",    "lavado.png",    "adj.calificat."),
("adj.calificat.-022", "quebrado",  "quebrado.png",  "adj.calificat."),
("adj.calificat.-023", "muerto",    "muerto.png",    "adj.calificat."),
("adj.calificat.-024", "verde",     "verde.png",     "adj.calificat."),
("adj.calificat.-025", "húmedo",    "húmedo.png",    "adj.calificat."),
("adj.calificat.-026", "negro",     "negro.png",     "adj.calificat."),
("adj.calificat.-027", "rojo",      "rojo.png",      "adj.calificat."),
("adj.calificat.-028", "blanco",    "blanco.png",    "adj.calificat."),
("adj.calificat.-029", "gris",      "gris.png",      "adj.calificat."),
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.29, 30, 31
("adj.núm.card.-001", "uno",                   "uno.png",                   "adj.núm.card."),
("adj.núm.card.-002", "dos",                   "dos.png",                   "adj.núm.card."),
("adj.núm.card.-003", "tres",                  "tres.png",                  "adj.núm.card."),
("adj.núm.card.-004", "cuatro",                "cuatro.png",                "adj.núm.card."),
("adj.núm.card.-005", "cinco",                 "cinco.png",                 "adj.núm.card."),
("adj.núm.card.-006", "seis",                  "seis.png",                  "adj.núm.card."),
("adj.núm.card.-007", "siete",                 "siete.png",                 "adj.núm.card."),
("adj.núm.card.-008", "ocho",                  "ocho.png",                  "adj.núm.card."),
("adj.núm.card.-009", "nueve",                 "nueve.png",                 "adj.núm.card."),
("adj.núm.card.-010", "diez",                  "diez.png",                  "adj.núm.card."),
("adj.núm.card.-011", "once",                  "once.png",                  "adj.núm.card."),
("adj.núm.card.-012", "doce",                  "doce.png",                  "adj.núm.card."),
("adj.núm.card.-013", "trece",                 "trece.png",                 "adj.núm.card."),
("adj.núm.card.-014", "catorce",               "catorce.png",               "adj.núm.card."),
("adj.núm.card.-015", "quince",                "quince.png",                "adj.núm.card."),
("adj.núm.card.-016", "dieciséis",             "dieciséis.png",             "adj.núm.card."),
("adj.núm.card.-017", "diecisiete",            "diecisiete.png",            "adj.núm.card."),
("adj.núm.card.-018", "dieciocho",             "dieciocho.png",             "adj.núm.card."),
("adj.núm.card.-019", "diecinueve",            "diecinueve.png",            "adj.núm.card."),
("adj.núm.card.-020", "veinte",                "veinte.png",                "adj.núm.card."),
("adj.núm.card.-021", "veintiuno",             "veintiuno.png",             "adj.núm.card."),
("adj.núm.card.-022", "veintidós",             "veintidós.png",             "adj.núm.card."),
("adj.núm.card.-023", "treinta",               "treinta.png",               "adj.núm.card."),
("adj.núm.card.-024", "treinta y uno",         "treinta y uno.png",         "adj.núm.card."),
("adj.núm.card.-025", "cuarenta",              "cuarenta.png",              "adj.núm.card."),
("adj.núm.card.-026", "sesenta",               "sesenta.png",               "adj.núm.card."),
("adj.núm.card.-027", "ochenta",               "ochenta.png",               "adj.núm.card."),
("adj.núm.card.-028", "cien",                  "cien.png",                  "adj.núm.card."),
("adj.núm.card.-029", "ciento veinte",         "ciento veinte.png",         "adj.núm.card."),
("adj.núm.card.-030", "ciento cuarenta",       "ciento cuarenta.png",       "adj.núm.card."),
("adj.núm.card.-031", "ciento sesenta",        "ciento sesenta.png",        "adj.núm.card."),
("adj.núm.card.-032", "ciento ochenta",        "ciento ochenta.png",        "adj.núm.card."),
("adj.núm.card.-033", "doscientos",            "doscientos.png",            "adj.núm.card."),
("adj.núm.card.-034", "trescientos",           "trescientos.png",           "adj.núm.card."),
("adj.núm.card.-035", "cuatrocientos",         "cuatrocientos.png",         "adj.núm.card."),
("adj.núm.card.-036", "cuatrocientos uno",     "cuatrocientos uno.png",     "adj.núm.card."),
("adj.núm.card.-037", "cuatrocientos dos",     "cuatrocientos dos.png",     "adj.núm.card."),
("adj.núm.card.-038", "ochocientos",           "ochocientos.png",           "adj.núm.card."),
("adj.núm.card.-039", "mil doscientos",        "mil doscientos.png",        "adj.núm.card."),
("adj.núm.card.-040", "mil seiscientos",       "mil seiscientos.png",       "adj.núm.card."),
("adj.núm.card.-041", "dos mil",               "dos mil.png",               "adj.núm.card."),
("adj.núm.card.-042", "dos mil cuatrocientos", "dos mil cuatrocientos.png", "adj.núm.card."),
("adj.núm.card.-043", "dos mil ochocientos",   "dos mil ochocientos.png",   "adj.núm.card."),
("adj.núm.card.-044", "tres mil doscientos",   "tres mil doscientos.png",   "adj.núm.card."),
("adj.núm.card.-045", "tres mil seiscientos",  "tres mil seiscientos.png",  "adj.núm.card."),
("adj.núm.card.-046", "cuatro mil",            "cuatro mil.png",            "adj.núm.card."),
("adj.núm.card.-047", "seis mil",              "seis mil.png",              "adj.núm.card."),
("adj.núm.card.-048", "ocho mil",              "ocho mil.png",              "adj.núm.card."),
("adj.núm.card.-049", "ocho mil uno",          "ocho mil uno.png",          "adj.núm.card."),
("adj.núm.card.-050", "ocho mil dos",          "ocho mil dos.png",          "adj.núm.card."),
("adj.núm.card.-051", "dieciséis mil",         "dieciséis mil.png",         "adj.núm.card."),
("adj.núm.card.-052", "veinticuatromil",       "veinticuatromil.png",       "adj.núm.card.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES
("adj.núm.ord.-01", "primero", "primero.png", "adj.núm.ord."),
("adj.núm.ord.-02", "segundo", "segundo.png", "adj.núm.ord."),
("adj.núm.ord.-03", "tercero", "tercero.png", "adj.núm.ord."),
("adj.núm.ord.-04", "cuarto",  "cuarto.png",  "adj.núm.ord."),
("adj.núm.ord.-05", "quinto",  "quinto.png",  "adj.núm.ord."),
("adj.núm.ord.-06", "sexto",   "sexto.png",   "adj.núm.ord."),
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.50
("compl.xxxxxx-000-000-001", "a (costa tuya)",           "a (costa tuya).png",           "compl."),
("prep.xxxxxxx-000-000-002", "a (la orilla del río)",    "a (la orilla del río).png",    "prep."),
("prep.compl.x-000-000-003", "a (orillas del río)",      "a (orillas del río).png",      "prep.compl."),
("compl.xxxxxx-000-000-004", "a (ustedes les dirán)",    "a (ustedes les dirán).png",    "compl."),
("compl.xxxxxx-000-000-005", "a (ustedes les-)",         "a (ustedes les-).png",         "compl."),
("prep.compl.x-000-000-006", "a (ellos, los, las, les)", "a (ellos, los, las, les).png", "prep.compl."),
("compl.xxxxxx-000-000-007", "a lo mejor",               "a lo mejor.png",               "compl."),
("compl.xxxxxx-000-000-008", "a lo mejor no",            "a lo mejor no.png",            "compl."),
("compl.xxxxxx-000-000-009", "a lo mejor si",            "a lo mejor si.png",            "compl."),
("v.t.xxxxxxxx-000-000-010", "a mercadear",              "a mercadear.png",              "v.t."),
("pref.xxxxxxx-000-000-011", "a mí,me",                  "a mí,me.png",                  "pref."),
("prep.compl.x-000-000-012", "a nosotros",               "a nosotros.png",               "prep.compl."),
("interj.xxxxx-000-000-013", "a poco (admiración)",      "a poco (admiración).png",      "interj."),
("conj.xxxxxxx-000-000-014", "a poco sí",                "a poco sí.png",                "conj."),
("pref.xxxxxxx-000-000-015", "a ti",                     "a ti.png",                     "pref."),
("compl.xxxxxx-000-000-016", "a ustedes",                "a ustedes.png",                "compl."),
("pref.prnl.xx-000-000-017", "a, al, el, lo, le, la",    "a, al, el, lo, le, la.png",    "pref.prnl."),
("adv.xxxxxxxx-000-000-018", "abajo",                    "abajo.png",                    "adv."),
("v.i.v.t.xxxx-000-000-019", "abandona (se)",            "abandona (se).png",            "v.i.v.t."),
("adj.xxxxxxxx-000-000-020", "abandonado,a",             "abandonado,a.png",             "adj."),
("v.i.pret.xxx-000-000-021", "abandonó",                 "abandonó.png",                 "v.i.pret."),
("s.xxxxxxxxxx-000-000-022", "abceso dental",            "abceso dental.png",            "s."),
("s.xxxxxxxxxx-000-000-023", "abceso (infección)",       "abceso (infección).png",       "s."),
("s.compl.xxxx-000-000-024", "abdomen delgado, flaco",   "abdomen delgado, flaco.png",   "s.compl."),
("s.xxxxxxxxxx-000-000-025", "abdomen grande",           "abdomen grande.png",           "s."),
("s.xxxxxxxxxx-000-000-026", "abdomen inflado",          "abdomen inflado.png",          "s."),
("s.xxxxxxxxxx-000-000-027", "abdomen",                  "abdomen.png",                  "s."),
("adj.xxxxxxxx-000-000-028", "abierto,a",                "abierto,a.png",                "adj."),
("s.xxxxxxxxxx-000-000-029", "aborto",                   "aborto.png",                   "s."),
("imper.indic.-000-000-030", "abraza (lo) (del cuello)", "abraza (lo) (del cuello).png", "imper.indic."),
("v.t.pres.xxx-000-000-031", "abraza",                   "abraza.png",                   "v.t.pres."),
("v.t.ger.xxxx-000-000-032", "abrazando",                "abrazando.png",                "v.t.ger."),
("v.t.xxxxxxxx-000-000-033", "abrazar",                  "abrazar.png",                  "v.t."),
("v.t.fut.xxxx-000-000-034", "abrazará",                 "abrazará.png",                 "v.t.fut."),
("v.t.pret.xxx-000-000-035", "abrazó",                   "abrazó.png",                   "v.t.pret."),
("v.t.compl.xx-000-000-036", "abre (la boca)",           "abre (la boca).png",           "v.t.compl."),
("v.t.imper.xx-000-000-037", "ábrelo",                   "ábrelo.png",                   "v.t.imper."),
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.51
("vt.ger.xxxxx-000-000-038", "abriendo",                                       "abriendo.png",                                        "vt.ger."),
("vt.pret.xxxx-000-000-039", "abrió",                                          "abrió.png",                                           "vt.pret."),
("v.t.xxxxxxxx-000-000-040", "abrir (los ojos)",                               "abrir (los ojos).png",                                "v.t."),
("v.t.xxxxxxxx-000-000-041", "abrir",                                          "abrir.png",                                           "v.t."),
("v.t.fut.xxxx-000-000-042", "abrirá (la boca)",                               "abrirá (la boca).png",                                "v.t.fut.")
("v.t.fut.xxxx-000-000-043", "abrirá",                                         "abrirá.png",                                          "v.t.fut."),
("v.t.xxxxxxxx-000-000-044", "absorber (agua)",                                "absorber (agua).png",                                 "v.t."),
("s.xxxxxxxxxx-000-000-045", "abuelita",                                       "abuelita.png",                                        "s."),
("s.xxxxxxxxxx-000-000-046", "abuelo",                                         "abuelo.png",                                          "s."),
("v.i.pres.xxx-000-000-047", "abunda",                                         "abunda.png",                                          "v.i.pres."),
("s.compl.xxxx-000-000-048", "abundancia (de epazote)",                        "abundancia (de epazote).png",                         "s.compl."),
("s.compl.xxxx-000-000-049", "abundancia (de hierba)",                         "abundancia (de hierba).png",                          "s.compl."),
("adj.xxxxxxxx-000-000-050", "académico,a (maestro)",                          "académico,a (maestro).png",                           "adj."),
("s.xxxxxxxxxx-000-000-051", "acahual (tierra en descanso)",                   "acahual (tierra en descanso).png",                    "s."),
("v.t.fut.xxxx-000-000-052", "acariciará",                                     "acariciará.png",                                      "v.t.fut."),
("v.t.xxxxxxxx-000-000-053", "acariciar",                                      "acariciar.png",                                       "v.t."),
("v.t.pres.xxx-000-000-054", "acaricio (lo)",                                  "acaricio (lo).png",                                   "v.t.pres."),
("s.xxxxxxxxxx-000-000-055", "ácaro",                                          "ácaro.png",                                           "s."),
("v.t.pres.xxx-000-000-056", "acarrea",                                        "acarrea.png",                                         "v.t.pres."),
("v.t.xxxxxxxx-000-000-057", "acarrear",                                       "acarrear.png",                                        "v.t."),
("v.t.fut.xxxx-000-000-058", "acarreará",                                      "acarreará.png",                                       "v.t.fut."),
("v.t.pres.s.x-000-000-059", "acarreo",                                        "acarreo.png",                                         "v.t.pres.s."),
("adv.xxxxxxxx-000-000-060", "acaso",                                          "acaso.png",                                           "adv."),
("v.t.pres.xxx-000-000-061", "acecha",                                         "acecha.png",                                          "v.t.pres."),
("v.i.pres.xxx-000-000-062", "acedar (se)",                                    "acedar (se).png",                                     "v.i.pres."),
("v.i.imper.xx-000-000-063", "acéptalo",                                       "acéptalo.png",                                        "v.i.imper."),
("v.i.xxxxxxxx-000-000-064", "aceptar",                                        "aceptar.png",                                         "v.i."),
("v.t.v.i.fut.-000-000-065", "aceptará",                                       "aceptará.png",                                        "v.t.v.i.fut."),
("v.t.pret.xxx-000-000-066", "aceptó (lo)",                                    "aceptó (lo).png",                                     "v.t.pret."),
("s.xxxxxxxxxx-000-000-067", "achiote",                                        "achiote.png",                                         "s."),
("adj.xxxxxxxx-000-000-068", "ácido,a",                                        "ácido,a.png",                                         "adj."),
("v.i.xxxxxxxx-000-000-069", "acolchar (se)",                                  "acolchar (se).png",                                   "v.i."),
("v.i.pres.xxx-000-000-070", "acongoja",                                       "acongoja.png",                                        "v.i.pres."),
("v.i.xxxxxxxx-000-000-071", "acostar",                                        "acostar.png",                                         "v.i."),
("v.i.fut.xxxx-000-000-072", "acostará (se)",                                  "acostará (se).png",                                   "v.i.fut."),
("v.i.xxxxxxxx-000-000-073", "acostar (se)",                                   "acostar (se).png",                                    "v.i."),
("v.i.xxxxxxxx-000-000-074", "acostar (se, boca abajo)",                       "acostar (se, boca abajo).png",                        "v.i."),
("v.t.xxxxxxxx-000-000-075", "acto de ordir los hilos",                        "acto de ordir los hilos.png",                         "v.t."),
("v.t.xxxxxxxx-000-000-076", "acto de separar los hilos",                      "acto de separar los hilos.png",                       "v.t."),
("v.t.xxxxxxxx-000-000-077", "acto de sujetar los hilosal xiotl, en el telar", "acto de sujetar los hilosal xiotl, en el telar.png",  "v.t.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.52
("v.i.imper.xxxxx-000-000-078", "acuéstate",         "acuéstate.png",         "v.i.imper."),
("v.i.xxxxxxxxxxx-000-000-079", "acurrucar",         "acurrucar.png",         "v.i."),
("adj.xxxxxxxxxxx-000-000-080", "adinerado,a",       "adinerado,a.png",       "adj."),
("interj.xxxxxxxx-000-000-081", "adiós (despedida)", "adiós (despedida).png", "interj."),
("adj.xxxxxxxxxxx-000-000-082", "adivino,a",         "adivino,a.png",         "adj."),
("s.xxxxxxxxxxxxx-000-000-083", "adobe",             "adobe.png",             "s."),
("s.xxxxxxxxxxxxx-000-000-084", "adolescencia",      "adolescencia.png",      "s."),
("adj.xxxxxxxxxxx-000-000-085", "adormilado,a",      "adormilado,a.png",      "adj."),
("v.t.pres.xxxxxx-000-000-086", "adorna",            "adorna.png",            "v.t.pres."),
("v.t.fut.xxxxxxx-000-000-087", "adornará",          "adornará.png",          "v.t.fut."),
("s.xxxxxxxxxxxxx-000-000-088", "adorno",            "adorno.png",            "s."),
("v.t.pret.xxxxxx-000-000-089", "adornó",            "adornó.png",            "v.t.pret."),
("adj.xxxxxxxxxxx-000-000-090", "adultero,a",        "adultero,a.png",        "adj."),
("v.t.pres.xxxxxx-000-000-091", "afila",             "afila.png",             "v.t.pres."),
("adj.xxxxxxxxxxx-000-000-092", "afilado,a",         "afilado,a.png",         "adj."),
("v.t.pres.xxxxxx-000-000-093", "afloja",            "afloja.png",            "v.t.pres."),
("v.t.ger.xxxxxxx-000-000-094", "aflojando",         "aflojando.png",         "v.t.ger."),
("v.t.pret.compl.-000-000-095", "aflojar (fue a)",   "aflojar (fue a).png",   "v.t.pret.compl."),
("v.t.pret.compl.-000-000-096", "aflojar (vino a)",  "aflojar (vino a).png",  "v.t.pret.compl."),
("v.t.xxxxxxxxxxx-000-000-097", "aflojar",           "aflojar.png",           "v.t."),
("v.t.fut.xxxxxxx-000-000-098", "aflojará",          "aflojará.png",          "v.t.fut."),
("v.t.pospr.xxxxx-000-000-099", "aflojaría",         "aflojaría.png",         "v.t.pospr."),
("v.t.imper.xxxxx-000-000-100", "aflójelo",          "aflójelo.png",          "v.t.imper."),
("v.t.pret.xxxxxx-000-000-101", "aflojó (se)",       "aflojó (se).png",       "v.t.pret."),
("v.i.pres.xxxxxx-000-000-102", "agacha (se)",       "agacha (se).png",       "v.i.pres."),
("v.i.xxxxxxxxxxx-000-000-103", "agacharse",         "agacharse.png",         "v.i."),
("v.t.pres.xxxxxx-000-000-104", "agarra",            "agarra.png",            "v.t.pres."),
("adj.xxxxxxxxxxx-000-000-105", "agarrado,a",        "agarrado,a.png",        "adj."),
("v.t. imper.xxxx-000-000-106", "agárralo",          "agárralo.png",          "v.t. imper."),
("v.t.compl.xxxxx-000-000-107", "agarrar (fue a)",   "agarrar (fue a).png",   "v.t.compl."),
("v.t.compl.xxxxx-000-000-108", "agarrar (vino a)",  "agarrar (vino a).png",  "v.t.compl."),
("v.t.fut.xxxxxxx-000-000-109", "agarrará",          "agarrará.png",          "v.t.fut."),
("v.t.pospr.xxxxx-000-000-110", "agarraría",         "agarraría.png",         "v.t.pospr."),
("v.t.pret.xxxxxx-000-000-111", "agarró (lo)",       "agarró (lo).png",       "v.t.pret."),
("v.t.pret.xxxxxx-000-000-112", "agarró",            "agarró.png",            "v.t.pret."),
("adj.xxxxxxxxxxx-000-000-113", "agrio,a",           "agrio,a.png",           "adj."),
("s.xxxxxxxxxxxxx-000-000-114", "agua",              "agua.png",              "s."),
("s.xxxxxxxxxxxxx-000-000-115", "agua salada",       "agua salada.png",       "s."),
("s.xxxxxxxxxxxxx-000-000-116", "agua limpia",       "agua limpia.png",       "s."),
("s.xxxxxxxxxxxxx-000-000-117", "agua hervida",      "agua hervida.png",      "s."),
("s.xxxxxxxxxxxxx-000-000-118", "agua fría",         "agua fría.png",         "s."),
("s.xxxxxxxxxxxxx-000-000-119", "agua estancada",    "agua estancada.png",    "s."),
("s.xxxxxxxxxxxxx-000-000-120", "agua dulce",        "agua dulce.png",        "s."),
("s.xxxxxxxxxxxxx-000-000-121", "agua de chile",     "agua de chile.png",     "s.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.60
("v.i.copr.xxxxxx-000-000-122", "bailaba",               "bailaba.png",               "v.i.copr."),
("adj.xxxxxxxxxxx-000-000-123", "bailador,a",            "bailador,a.png",            "adj."),
("v.i.ger.compl.x-000-000-124", "bailando,está",         "bailando,está.png",         "v.i.ger.compl."),
("v.i.fut.xxxxxxx-000-000-125", "bailará",               "bailará.png",               "v.i.fut."),
("v.i.pospr.xxxxx-000-000-126", "bailaría",              "bailaría.png",              "v.i.pospr."),
("s.xxxxxxxxxxxxx-000-000-127", "baile",                 "baile.png",                 "s."),
("v.i.pret.xxxxxx-000-000-128", "bailó",                 "bailó.png",                 "v.i.pret."),
("v.i.pret.xxxxxx-000-000-129", "baja",                  "baja.png",                  "v.i.pret."),
("v.t.imper.xxxxx-000-000-130", "bájale",                "bájale.png",                "v.t.imper."),
("v.i.pres.xxxxxx-000-000-131", "bajamos",               "bajamos.png",               "v.i.pres."),
("v.i.v.t.xxxxxxx-000-000-132", "bajar",                 "bajar.png",                 "v.i.v.t."),
("v.i.pret.xxxxxx-000-000-133", "bajaron",               "bajaron.png",               "v.i.pret."),
("v.i.imper.xxxxx-000-000-134", "bajen",                 "bajen.png",                 "v.i.imper."),
("adj.xxxxxxxxxxx-000-000-135", "bajo,a",                "bajo,a.png",                "adj."),
("adj.prep.xxxxxx-000-000-136", "bajo (el agua)",        "bajo (el agua).png",        "adj.prep."),
("v.i.pres.xxxxxx-000-000-137", "baña (se) en temascal", "baña (se) en temascal.png", "v.i.pres."),
("v.i.v.t.pres.xx-000-000-138", "baña",                  "baña.png",                  "v.i.v.t.pres."),
("v.i.imper.xxxxx-000-000-139", "báñate",                "báñate.png",                "v.i.imper."),
("v.i.imper.rev.x-000-000-140", "bañese usted",          "bañese usted.png",          "v.i.imper.rev."),
("s.xxxxxxxxxxxxx-000-000-141", "baño de vapor",         "baño de vapor.png",         "s."),
("adj.xxxxxxxxxxx-000-000-142", "barato,a",              "barato,a.png",              "adj."),
("s.xxxxxxxxxxxxx-000-000-143", "barba",                 "barba.png",                 "s."),
("s.xxxxxxxxxxxxx-000-000-144", "barba (de ocote)",      "barba (de ocote).png",      "s."),
("s.xxxxxxxxxxxxx-000-000-145", "barbilla",              "barbilla.png",              "s."),
("s.xxxxxxxxxxxxx-000-000-146", "barco,a",               "barco,a.png",               "s."),
("s.xxxxxxxxxxxxx-000-000-147", "barranca,o",            "barranca,o.png",            "s."),
("s.xxxxxxxxxxxxx-000-000-148", "barranquilla",          "barranquilla.png",          "s."),
("v.t.xxxxxxxxxxx-000-000-149", "barre",                 "barre.png",                 "v.t."),
("adj.xxxxxxxxxxx-000-000-150", "barredor,a",            "barredor,a.png",            "adj."),
("v.t.xxxxxxxxxxx-000-000-151", "barrer",                "barrer.png",                "v.t."),
("v.t.fut.xxxxxxx-000-000-152", "barrerá",               "barrerá.png",               "v.t.fut."),
("v.t.copr.xxxxxx-000-000-153", "barría",                "barría.png",                "v.t.copr."),
("adj.xxxxxxxxxxx-000-000-154", "barrido,a",             "barrido,a.png",             "adj."),
("s.xxxxxxxxxxxxx-000-000-155", "barriga",               "barriga.png",               "s."),
("s.xxxxxxxxxxxxx-000-000-156", "barrio",                "barrio.png",                "s."),
("v.t.pospr.xxxxx-000-000-157", "barriría",              "barriría.png",              "v.t.pospr."),
("s.xxxxxxxxxxxxx-000-000-158", "basura",                "basura.png",                "s."),
("v.t.xxxxxxxxxxx-000-000-159", "batir",                 "batir.png",                 "v.t."),
("v.t.fut.xxxxxxx-000-000-160", "batirá",                "batirá.png",                "v.t.fut."),
("v.t.imper.xxxxx-000-000-161", "bautícelo",             "bautícelo.png",             "v.t.imper."),
("s.v.t.pret.xxxx-000-000-162", "bautizó",               "bautizó.png",               "s.v.t.pret."),
("v.t.imper.xxxxx-000-000-163", "beba (agua)",           "beba (agua).png",           "v.t.imper."),
("compl.rev.xxxxx-000-000-164", "beba (usted)",          "beba (usted).png",          "compl.rev."),
("v.i.imper.xxxxx-000-000-165", "beba (lo) usted",       "beba (lo) usted.png",       "v.i.imper."),