INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.16, 17
("v.-000-001", "ver",       "ver.png",      "v."),
("v.-000-002", "querer",    "querer.png",   "v."),
("v.-000-003", "escuchar",  "escuchar.png", "v."),
("v.-000-004", "agarrar",   "agarrar.png",  "v."),
("v.-000-005", "hacer",     "hacer.png",    "v."),
("v.-000-006", "comer",     "comer.png",    "v."),
("v.-000-007", "beber",     "beber.png",    "v."),
("v.-000-008", "amar",      "amar.png",     "v."),
("v.-000-009", "dormir",   "dormir.png",    "v."),
("v.-000-010", "caminar",  "caminar.png",   "v."),
("v.-000-011", "bailar",   "bailar.png",    "v."),
("v.-000-012", "llorar",   "llorar.png",    "v."),
("v.-000-013", "reír",     "reír.png",      "v."),
("v.-000-014", "trabajar", "trabajar.png",  "v."),
("v.-000-015", "escribir", "escribir.png",  "v."),
("v.-000-016", "contar",   "contar.png",    "v."),
("v.-000-017", "cortar",   "cortar.png",    "v."),
("v.-000-018", "barrer",   "barrer.png",    "v."),
("v.-000-019", "decir",    "decir.png",     "v."),
("v.-000-020", "coser",    "coser.png",     "v."),
("v.-000-021", "tener",    "tener.png",     "v."),
("v.-000-022", "vender",   "vender.png",    "v."),
("v.-000-023", "ganar",    "ganar.png",     "v."),
("v.-000-024", "enojar",   "enojar.png",    "v."),
("v.-000-025", "gritar",   "gritar.png",    "v."),
("v.-000-026", "jugar",    "jugar.png",     "v.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.20
("pron.pers.-01", "yo",       "yo.png",       "pron.pers."),
("pron.pers.-02", "tú",       "tú.png",       "pron.pers."),
("pron.pers.-03", "él",       "él.png",       "pron.pers."),
("pron.pers.-04", "nosotros", "nosotros.png", "pron.pers."),
("pron.pers.-05", "ustedes",  "ustedes.png",  "pron.pers."),
("pron.pers.-06", "ellos",    "ellos.png",    "pron.pers.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.22
("pron.dem.-01", "este, esta, esto (objeto)", "este.png",  "pron.dem."),
("pron.dem.-02", "ese, esa, eso (objeto)",    "ese.png",   "pron.dem."),
("pron.dem.-03", "aquel, aquello",            "aquel.png", "pron.dem."),
("pron.dem.-04", "allá",                      "allá.png",  "pron.dem.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES  --pag.23
("pron.indef.-01", "quien",      "yo.png", "pron.indef."),
("pron.indef.-02", "algunos",    "tú.png", "pron.indef."),
("pron.indef.-03", "otro",       "tú.png", "pron.indef."),
("pron.indef.-04", "cualquiera", "él.png", "pron.indef."),
("pron.indef.-05", "nadie",      "él.png", "pron.indef.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES  --pag.24
("pref.prnl.suj.-01", "primera persona del singular", "primera persona del singular.png", "pron.indef."), --pag.24
("pref.prnl.suj.-02", "segunda persona del singular", "segunda persona del singular.png", "pron.indef."),
("pref.prnl.suj.-03", "primera persona del plural",   "primera persona del plural.png",   "pron.indef."),
("pref.prnl.suj.-04", "segunda persona del plural",   "segunda persona del plural.png",   "pron.indef.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES  --pag.24
("pref.prnl.-01", "mi me",          "mi me.png",           "pref.prnl."),
("pref.prnl.-02", "a ti te",        "a ti te.png",         "pref.prnl."),
("pref.prnl.-03", "a él le",        "a él le.png",         "pref.prnl."),
("pref.prnl.-04", "a nosotros nos", "a nosotros nos.png",  "pref.prnl."),
("pref.prnl.-05", "a ustedes les",  "a ustedes les.png",   "pref.prnl."),
("pref.prnl.-06", "a ellos ",       "a ellos .png",        "pref.prnl.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES  --pag.25
("pref.pos.-01", "mío",        "mío.png",        "pref.pos."),
("pref.pos.-02", "tuyo",       "tuyo.png",       "pref.pos."),
("pref.pos.-03", "suyo",       "suyo.png",       "pref.pos."),
("pref.pos.-04", "nuestro" ,   "nuestro.png",    "pref.pos."),
("pref.pos.-05", "de ustedes", "de ustedes.png", "pref.pos."),
("pref.pos.-06", "de ellos",   "de ellos.png",   "pref.pos.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES  --pag.25
("pref.prnl.r-01", "a mí mismo",        "a mí mismo.png",        "pref.prnl.r"),
("pref.prnl.r-02", "a tí mismo",        "a tí mismo.png",        "pref.prnl.r"),
("pref.prnl.r-03", "a él mismo",        "a él mismo.png",        "pref.prnl.r"),
("pref.prnl.r-04", "a nosotros mismos", "a nosotros mismos.png", "pref.prnl.r"),
("pref.prnl.r-05", "a ustedes mismos",  "a ustedes mismos.png",  "pref.prnl.r");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES  --pag.26
("pref.indef.-01", "se refiere a pertenencia de alguien", "se refiere a pertenencia de alguien.png", "pref.indef."),
("pref.indef.-02", "prefijo de acción",                   "prefijo de acción.png",                   "pref.indef.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.26, 27, 28
("adv.-001", "lejos",                           "lejos.png",                           "adv."),
("adv.-002", "cerca",                           "cerca.png",                           "adv."),
("adv.-003", "pasado mañana",                   "pasado mañana.png",                   "adv."),
("adv.-004", "bien",                            "bien.png",                            "adv."),
("adv.-005", "despacio",                        "despacio.png",                        "adv."),
("adv.-006", "siempre",                         "siempre.png",                         "adv."),
("adv.-007", "nunca",                           "nunca.png",                           "adv."),
("adv.-008", "posiblemente",                    "posiblemente.png",                    "adv."),
("adv.-009", "nada",                            "nada.png",                            "adv."),
("adv.-010", "de nada",                         "de nada.png",                         "adv."),
("adv.-011", "donde",                           "donde.png",                           "adv."),
("adv.-012", "aquí",                            "aquí.png",                            "adv."),
("adv.-013", "allá",                            "allá.png",                            "adv."),
("adv.-014", "abajo",                           "abajo.png",                           "adv."),
("adv.-015", "arriba",                          "arriba.png",                          "adv."),
("adv.-016", "ya tardó",                        "ya tardó.png",                        "adv."),
("adv.-017", "aquí",                            "aquí.png",                            "adv."),
("adv.-018", "por acá",                         "por acá.png",                         "adv."),
("adv.-019", "lejos",                           "lejos.png",                           "adv."),
("adv.-020", "cuando",                          "cuando.png",                          "adv."),
("adv.-021", "hoy",                             "hoy.png",                             "adv."),
("adv.-022", "mañana",                          "mañana.png",                          "adv."),
("adv.-023", "ayer",                            "ayer.png",                            "adv."),
("adv.-024", "como",                            "como.png",                            "adv."),
("adv.-025", "así",                             "así.png",                             "adv."),
("adv.-026", "pronto",                          "pronto.png",                          "adv."),
("adv.-027", "duro",                            "duro.png",                            "adv."),
("adv.-028", "fuerte",                          "fuerte.png",                          "adv."),
("adv.-029", "verdadero",                       "verdadero.png",                       "adv."),
("adv.-030", "si",                              "si.png",                              "adv."),
("adv.-031", "también",                         "también.png",                         "adv."),
("adv.-032", "bonito",                          "bonito.png",                          "adv."),
("adv.-033", "correctamente",                   "correctamente.png",                   "adv."),
("adv.-034", "no",                              "no.png",                              "adv."),
("adv.-035", "aun no",                          "aun no.png",                          "adv."),
("adv.-036", "ya no",                           "ya no.png",                           "adv."),
("adv.-037", "nunca",                           "nunca.png",                           "adv."),
("adv.-038", "quién sabe (duda)",               "quién sabe (duda).png",               "adv."),
("adv.-039", "mucho",                           "mucho.png",                           "adv."),
("adv.-030", "poco",                            "poco.png",                            "adv."),
("adv.-040", "nada",                            "nada.png",                            "adv."),
("adv.-041", "muy",                             "muy.png",                             "adv."),
("adv.-042", "tal vez",                         "tal vez.png",                         "adv."),
("adv.-043", "aunque no",                       "aunque no.png",                       "adv."),
("adv.-044", "como es posible",                 "como es posible.png",                 "adv."),
("adv.-045", "y",                               "y.png",                               "adv."),
("adv.-046", "así",                             "así.png",                             "adv."),
("adv.-047", "por qué",                         "por qué.png",                         "adv."),
("adv.-048", "pues, porque",                    "pues, porque.png",                    "adv."),
("adv.-049", "junto a él",                      "junto a él.png",                      "adv."),
("adv.-050", "junto de ellos",                  "junto de ellos.png",                  "adv."),
("adv.-051", "sí (condicionante)",              "sí (condicionante).png",              "adv."),
("adv.-052", "cierto",                          "cierto.png",                          "adv."),
("adv.-053", "sí es cierto (condicionante)",    "sí es cierto (condicionante).png",    "adv."),
("adv.-054", "sí no es cierto (condicionante)", "sí no es cierto (condicionante).png", "adv."),
("adv.-055", "aunque",                          "aunque.png",                          "adv."),
("adv.-056", "eso dicen",                       "eso dicen.png",                       "adv."),
("adv.-057", "delgado",                         "delgado.png",                         "adv."),
("adv.-058", "más",                             "más.png",                             "adv."),
("adv.-059", "gordo",                           "gordo.png",                           "adv."),
("adv.-060", "largo",                           "largo.png",                           "adv."),
("adv.-061", "bajo (lugar)",                    "bajo (lugar).png",                    "adv."),
("adv.-062", "abajo",                           "abajo.png",                           "adv.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.28, 29
("adj.calificat.-001", "bonita",    "bonita.png",    "adj.calificat."),
("adj.calificat.-002", "chica",     "chica.png",     "adj.calificat."),
("adj.calificat.-003", "blanca",    "blanca.png",    "adj.calificat."),
("adj.calificat.-004", "limpia",    "limpia.png",    "adj.calificat."),
("adj.calificat.-005", "bella",     "bella.png",     "adj.calificat."),
("adj.calificat.-006", "redonda",   "redonda.png",   "adj.calificat."),
("adj.calificat.-007", "grande",    "grande.png",    "adj.calificat."),
("adj.calificat.-008", "roja",      "roja.png",      "adj.calificat."),
("adj.calificat.-009", "negro",     "negro.png",     "adj.calificat."),
("adj.calificat.-010", "pequeño",   "pequeño.png",   "adj.calificat."),
("adj.calificat.-011", "bravo",     "bravo.png",     "adj.calificat."),
("adj.calificat.-012", "miedoso",   "miedoso.png",   "adj.calificat."),
("adj.calificat.-013", "enojón",    "enojón.png",    "adj.calificat."),
("adj.calificat.-014", "grueso",    "grueso.png",    "adj.calificat."),
("adj.calificat.-015", "largo",     "largo.png",     "adj.calificat."),
("adj.calificat.-016", "fuerte",    "fuerte.png",    "adj.calificat."),
("adj.calificat.-017", "delgado",   "delgado.png",   "adj.calificat."),
("adj.calificat.-018", "resbaloso", "resbaloso.png", "adj.calificat."),
("adj.calificat.-019", "quebrado",  "quebrado.png",  "adj.calificat."),
("adj.calificat.-020", "hervido",   "hervido.png",   "adj.calificat."),
("adj.calificat.-021", "lavado",    "lavado.png",    "adj.calificat."),
("adj.calificat.-022", "quebrado",  "quebrado.png",  "adj.calificat."),
("adj.calificat.-023", "muerto",    "muerto.png",    "adj.calificat."),
("adj.calificat.-024", "verde",     "verde.png",     "adj.calificat."),
("adj.calificat.-025", "húmedo",    "húmedo.png",    "adj.calificat."),
("adj.calificat.-026", "negro",     "negro.png",     "adj.calificat."),
("adj.calificat.-027", "rojo",      "rojo.png",      "adj.calificat."),
("adj.calificat.-028", "blanco",    "blanco.png",    "adj.calificat."),
("adj.calificat.-029", "gris",      "gris.png",      "adj.calificat."),
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.29, 30, 31
("adj.núm.card.-001", "uno",                   "uno.png",                   "adj.núm.card."),
("adj.núm.card.-002", "dos",                   "dos.png",                   "adj.núm.card."),
("adj.núm.card.-003", "tres",                  "tres.png",                  "adj.núm.card."),
("adj.núm.card.-004", "cuatro",                "cuatro.png",                "adj.núm.card."),
("adj.núm.card.-005", "cinco",                 "cinco.png",                 "adj.núm.card."),
("adj.núm.card.-006", "seis",                  "seis.png",                  "adj.núm.card."),
("adj.núm.card.-007", "siete",                 "siete.png",                 "adj.núm.card."),
("adj.núm.card.-008", "ocho",                  "ocho.png",                  "adj.núm.card."),
("adj.núm.card.-009", "nueve",                 "nueve.png",                 "adj.núm.card."),
("adj.núm.card.-010", "diez",                  "diez.png",                  "adj.núm.card."),
("adj.núm.card.-011", "once",                  "once.png",                  "adj.núm.card."),
("adj.núm.card.-012", "doce",                  "doce.png",                  "adj.núm.card."),
("adj.núm.card.-013", "trece",                 "trece.png",                 "adj.núm.card."),
("adj.núm.card.-014", "catorce",               "catorce.png",               "adj.núm.card."),
("adj.núm.card.-015", "quince",                "quince.png",                "adj.núm.card."),
("adj.núm.card.-016", "dieciséis",             "dieciséis.png",             "adj.núm.card."),
("adj.núm.card.-017", "diecisiete",            "diecisiete.png",            "adj.núm.card."),
("adj.núm.card.-018", "dieciocho",             "dieciocho.png",             "adj.núm.card."),
("adj.núm.card.-019", "diecinueve",            "diecinueve.png",            "adj.núm.card."),
("adj.núm.card.-020", "veinte",                "veinte.png",                "adj.núm.card."),
("adj.núm.card.-021", "veintiuno",             "veintiuno.png",             "adj.núm.card."),
("adj.núm.card.-022", "veintidós",             "veintidós.png",             "adj.núm.card."),
("adj.núm.card.-023", "treinta",               "treinta.png",               "adj.núm.card."),
("adj.núm.card.-024", "treinta y uno",         "treinta y uno.png",         "adj.núm.card."),
("adj.núm.card.-025", "cuarenta",              "cuarenta.png",              "adj.núm.card."),
("adj.núm.card.-026", "sesenta",               "sesenta.png",               "adj.núm.card."),
("adj.núm.card.-027", "ochenta",               "ochenta.png",               "adj.núm.card."),
("adj.núm.card.-028", "cien",                  "cien.png",                  "adj.núm.card."),
("adj.núm.card.-029", "ciento veinte",         "ciento veinte.png",         "adj.núm.card."),
("adj.núm.card.-030", "ciento cuarenta",       "ciento cuarenta.png",       "adj.núm.card."),
("adj.núm.card.-031", "ciento sesenta",        "ciento sesenta.png",        "adj.núm.card."),
("adj.núm.card.-032", "ciento ochenta",        "ciento ochenta.png",        "adj.núm.card."),
("adj.núm.card.-033", "doscientos",            "doscientos.png",            "adj.núm.card."),
("adj.núm.card.-034", "trescientos",           "trescientos.png",           "adj.núm.card."),
("adj.núm.card.-035", "cuatrocientos",         "cuatrocientos.png",         "adj.núm.card."),
("adj.núm.card.-036", "cuatrocientos uno",     "cuatrocientos uno.png",     "adj.núm.card."),
("adj.núm.card.-037", "cuatrocientos dos",     "cuatrocientos dos.png",     "adj.núm.card."),
("adj.núm.card.-038", "ochocientos",           "ochocientos.png",           "adj.núm.card."),
("adj.núm.card.-039", "mil doscientos",        "mil doscientos.png",        "adj.núm.card."),
("adj.núm.card.-040", "mil seiscientos",       "mil seiscientos.png",       "adj.núm.card."),
("adj.núm.card.-041", "dos mil",               "dos mil.png",               "adj.núm.card."),
("adj.núm.card.-042", "dos mil cuatrocientos", "dos mil cuatrocientos.png", "adj.núm.card."),
("adj.núm.card.-043", "dos mil ochocientos",   "dos mil ochocientos.png",   "adj.núm.card."),
("adj.núm.card.-044", "tres mil doscientos",   "tres mil doscientos.png",   "adj.núm.card."),
("adj.núm.card.-045", "tres mil seiscientos",  "tres mil seiscientos.png",  "adj.núm.card."),
("adj.núm.card.-046", "cuatro mil",            "cuatro mil.png",            "adj.núm.card."),
("adj.núm.card.-047", "seis mil",              "seis mil.png",              "adj.núm.card."),
("adj.núm.card.-048", "ocho mil",              "ocho mil.png",              "adj.núm.card."),
("adj.núm.card.-049", "ocho mil uno",          "ocho mil uno.png",          "adj.núm.card."),
("adj.núm.card.-050", "ocho mil dos",          "ocho mil dos.png",          "adj.núm.card."),
("adj.núm.card.-051", "dieciséis mil",         "dieciséis mil.png",         "adj.núm.card."),
("adj.núm.card.-052", "veinticuatromil",       "veinticuatromil.png",       "adj.núm.card.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES
("adj.núm.ord.-01", "primero", "primero.png", "adj.núm.ord."),
("adj.núm.ord.-02", "segundo", "segundo.png", "adj.núm.ord."),
("adj.núm.ord.-03", "tercero", "tercero.png", "adj.núm.ord."),
("adj.núm.ord.-04", "cuarto",  "cuarto.png",  "adj.núm.ord."),
("adj.núm.ord.-05", "quinto",  "quinto.png",  "adj.núm.ord."),
("adj.núm.ord.-06", "sexto",   "sexto.png",   "adj.núm.ord."),
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.50
("compl.xxxxxx-000-000-001", "a (costa tuya)",           "a (costa tuya).png",           "compl."),
("prep.xxxxxxx-000-000-002", "a (la orilla del río)",    "a (la orilla del río).png",    "prep."),
("prep.compl.x-000-000-003", "a (orillas del río)",      "a (orillas del río).png",      "prep.compl."),
("compl.xxxxxx-000-000-004", "a (ustedes les dirán)",    "a (ustedes les dirán).png",    "compl."),
("compl.xxxxxx-000-000-005", "a (ustedes les-)",         "a (ustedes les-).png",         "compl."),
("prep.compl.x-000-000-006", "a (ellos, los, las, les)", "a (ellos, los, las, les).png", "prep.compl."),
("compl.xxxxxx-000-000-007", "a lo mejor",               "a lo mejor.png",               "compl."),
("compl.xxxxxx-000-000-008", "a lo mejor no",            "a lo mejor no.png",            "compl."),
("compl.xxxxxx-000-000-009", "a lo mejor si",            "a lo mejor si.png",            "compl."),
("v.t.xxxxxxxx-000-000-010", "a mercadear",              "a mercadear.png",              "v.t."),
("pref.xxxxxxx-000-000-011", "a mí,me",                  "a mí,me.png",                  "pref."),
("prep.compl.x-000-000-012", "a nosotros",               "a nosotros.png",               "prep.compl."),
("interj.xxxxx-000-000-013", "a poco (admiración)",      "a poco (admiración).png",      "interj."),
("conj.xxxxxxx-000-000-014", "a poco sí",                "a poco sí.png",                "conj."),
("pref.xxxxxxx-000-000-015", "a ti",                     "a ti.png",                     "pref."),
("compl.xxxxxx-000-000-016", "a ustedes",                "a ustedes.png",                "compl."),
("pref.prnl.xx-000-000-017", "a, al, el, lo, le, la",    "a, al, el, lo, le, la.png",    "pref.prnl."),
("adv.xxxxxxxx-000-000-018", "abajo",                    "abajo.png",                    "adv."),
("v.i.v.t.xxxx-000-000-019", "abandona (se)",            "abandona (se).png",            "v.i.v.t."),
("adj.xxxxxxxx-000-000-020", "abandonado,a",             "abandonado,a.png",             "adj."),
("v.i.pret.xxx-000-000-021", "abandonó",                 "abandonó.png",                 "v.i.pret."),
("s.xxxxxxxxxx-000-000-022", "abceso dental",            "abceso dental.png",            "s."),
("s.xxxxxxxxxx-000-000-023", "abceso (infección)",       "abceso (infección).png",       "s."),
("s.compl.xxxx-000-000-024", "abdomen delgado, flaco",   "abdomen delgado, flaco.png",   "s.compl."),
("s.xxxxxxxxxx-000-000-025", "abdomen grande",           "abdomen grande.png",           "s."),
("s.xxxxxxxxxx-000-000-026", "abdomen inflado",          "abdomen inflado.png",          "s."),
("s.xxxxxxxxxx-000-000-027", "abdomen",                  "abdomen.png",                  "s."),
("adj.xxxxxxxx-000-000-028", "abierto,a",                "abierto,a.png",                "adj."),
("s.xxxxxxxxxx-000-000-029", "aborto",                   "aborto.png",                   "s."),
("imper.indic.-000-000-030", "abraza (lo) (del cuello)", "abraza (lo) (del cuello).png", "imper.indic."),
("v.t.pres.xxx-000-000-031", "abraza",                   "abraza.png",                   "v.t.pres."),
("v.t.ger.xxxx-000-000-032", "abrazando",                "abrazando.png",                "v.t.ger."),
("v.t.xxxxxxxx-000-000-033", "abrazar",                  "abrazar.png",                  "v.t."),
("v.t.fut.xxxx-000-000-034", "abrazará",                 "abrazará.png",                 "v.t.fut."),
("v.t.pret.xxx-000-000-035", "abrazó",                   "abrazó.png",                   "v.t.pret."),
("v.t.compl.xx-000-000-036", "abre (la boca)",           "abre (la boca).png",           "v.t.compl."),
("v.t.imper.xx-000-000-037", "ábrelo",                   "ábrelo.png",                   "v.t.imper."),
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.51
("vt.ger.xxxxx-000-000-038", "abriendo",                                       "abriendo.png",                                        "vt.ger."),
("vt.pret.xxxx-000-000-039", "abrió",                                          "abrió.png",                                           "vt.pret."),
("v.t.xxxxxxxx-000-000-040", "abrir (los ojos)",                               "abrir (los ojos).png",                                "v.t."),
("v.t.xxxxxxxx-000-000-041", "abrir",                                          "abrir.png",                                           "v.t."),
("v.t.fut.xxxx-000-000-042", "abrirá (la boca)",                               "abrirá (la boca).png",                                "v.t.fut.")
("v.t.fut.xxxx-000-000-043", "abrirá",                                         "abrirá.png",                                          "v.t.fut."),
("v.t.xxxxxxxx-000-000-044", "absorber (agua)",                                "absorber (agua).png",                                 "v.t."),
("s.xxxxxxxxxx-000-000-045", "abuelita",                                       "abuelita.png",                                        "s."),
("s.xxxxxxxxxx-000-000-046", "abuelo",                                         "abuelo.png",                                          "s."),
("v.i.pres.xxx-000-000-047", "abunda",                                         "abunda.png",                                          "v.i.pres."),
("s.compl.xxxx-000-000-048", "abundancia (de epazote)",                        "abundancia (de epazote).png",                         "s.compl."),
("s.compl.xxxx-000-000-049", "abundancia (de hierba)",                         "abundancia (de hierba).png",                          "s.compl."),
("adj.xxxxxxxx-000-000-050", "académico,a (maestro)",                          "académico,a (maestro).png",                           "adj."),
("s.xxxxxxxxxx-000-000-051", "acahual (tierra en descanso)",                   "acahual (tierra en descanso).png",                    "s."),
("v.t.fut.xxxx-000-000-052", "acariciará",                                     "acariciará.png",                                      "v.t.fut."),
("v.t.xxxxxxxx-000-000-053", "acariciar",                                      "acariciar.png",                                       "v.t."),
("v.t.pres.xxx-000-000-054", "acaricio (lo)",                                  "acaricio (lo).png",                                   "v.t.pres."),
("s.xxxxxxxxxx-000-000-055", "ácaro",                                          "ácaro.png",                                           "s."),
("v.t.pres.xxx-000-000-056", "acarrea",                                        "acarrea.png",                                         "v.t.pres."),
("v.t.xxxxxxxx-000-000-057", "acarrear",                                       "acarrear.png",                                        "v.t."),
("v.t.fut.xxxx-000-000-058", "acarreará",                                      "acarreará.png",                                       "v.t.fut."),
("v.t.pres.s.x-000-000-059", "acarreo",                                        "acarreo.png",                                         "v.t.pres.s."),
("adv.xxxxxxxx-000-000-060", "acaso",                                          "acaso.png",                                           "adv."),
("v.t.pres.xxx-000-000-061", "acecha",                                         "acecha.png",                                          "v.t.pres."),
("v.i.pres.xxx-000-000-062", "acedar (se)",                                    "acedar (se).png",                                     "v.i.pres."),
("v.i.imper.xx-000-000-063", "acéptalo",                                       "acéptalo.png",                                        "v.i.imper."),
("v.i.xxxxxxxx-000-000-064", "aceptar",                                        "aceptar.png",                                         "v.i."),
("v.t.v.i.fut.-000-000-065", "aceptará",                                       "aceptará.png",                                        "v.t.v.i.fut."),
("v.t.pret.xxx-000-000-066", "aceptó (lo)",                                    "aceptó (lo).png",                                     "v.t.pret."),
("s.xxxxxxxxxx-000-000-067", "achiote",                                        "achiote.png",                                         "s."),
("adj.xxxxxxxx-000-000-068", "ácido,a",                                        "ácido,a.png",                                         "adj."),
("v.i.xxxxxxxx-000-000-069", "acolchar (se)",                                  "acolchar (se).png",                                   "v.i."),
("v.i.pres.xxx-000-000-070", "acongoja",                                       "acongoja.png",                                        "v.i.pres."),
("v.i.xxxxxxxx-000-000-071", "acostar",                                        "acostar.png",                                         "v.i."),
("v.i.fut.xxxx-000-000-072", "acostará (se)",                                  "acostará (se).png",                                   "v.i.fut."),
("v.i.xxxxxxxx-000-000-073", "acostar (se)",                                   "acostar (se).png",                                    "v.i."),
("v.i.xxxxxxxx-000-000-074", "acostar (se, boca abajo)",                       "acostar (se, boca abajo).png",                        "v.i."),
("v.t.xxxxxxxx-000-000-075", "acto de ordir los hilos",                        "acto de ordir los hilos.png",                         "v.t."),
("v.t.xxxxxxxx-000-000-076", "acto de separar los hilos",                      "acto de separar los hilos.png",                       "v.t."),
("v.t.xxxxxxxx-000-000-077", "acto de sujetar los hilosal xiotl, en el telar", "acto de sujetar los hilosal xiotl, en el telar.png",  "v.t.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.52
("v.i.imper.xxxxx-000-000-078", "acuéstate",         "acuéstate.png",         "v.i.imper."),
("v.i.xxxxxxxxxxx-000-000-079", "acurrucar",         "acurrucar.png",         "v.i."),
("adj.xxxxxxxxxxx-000-000-080", "adinerado,a",       "adinerado,a.png",       "adj."),
("interj.xxxxxxxx-000-000-081", "adiós (despedida)", "adiós (despedida).png", "interj."),
("adj.xxxxxxxxxxx-000-000-082", "adivino,a",         "adivino,a.png",         "adj."),
("s.xxxxxxxxxxxxx-000-000-083", "adobe",             "adobe.png",             "s."),
("s.xxxxxxxxxxxxx-000-000-084", "adolescencia",      "adolescencia.png",      "s."),
("adj.xxxxxxxxxxx-000-000-085", "adormilado,a",      "adormilado,a.png",      "adj."),
("v.t.pres.xxxxxx-000-000-086", "adorna",            "adorna.png",            "v.t.pres."),
("v.t.fut.xxxxxxx-000-000-087", "adornará",          "adornará.png",          "v.t.fut."),
("s.xxxxxxxxxxxxx-000-000-088", "adorno",            "adorno.png",            "s."),
("v.t.pret.xxxxxx-000-000-089", "adornó",            "adornó.png",            "v.t.pret."),
("adj.xxxxxxxxxxx-000-000-090", "adultero,a",        "adultero,a.png",        "adj."),
("v.t.pres.xxxxxx-000-000-091", "afila",             "afila.png",             "v.t.pres."),
("adj.xxxxxxxxxxx-000-000-092", "afilado,a",         "afilado,a.png",         "adj."),
("v.t.pres.xxxxxx-000-000-093", "afloja",            "afloja.png",            "v.t.pres."),
("v.t.ger.xxxxxxx-000-000-094", "aflojando",         "aflojando.png",         "v.t.ger."),
("v.t.pret.compl.-000-000-095", "aflojar (fue a)",   "aflojar (fue a).png",   "v.t.pret.compl."),
("v.t.pret.compl.-000-000-096", "aflojar (vino a)",  "aflojar (vino a).png",  "v.t.pret.compl."),
("v.t.xxxxxxxxxxx-000-000-097", "aflojar",           "aflojar.png",           "v.t."),
("v.t.fut.xxxxxxx-000-000-098", "aflojará",          "aflojará.png",          "v.t.fut."),
("v.t.pospr.xxxxx-000-000-099", "aflojaría",         "aflojaría.png",         "v.t.pospr."),
("v.t.imper.xxxxx-000-000-100", "aflójelo",          "aflójelo.png",          "v.t.imper."),
("v.t.pret.xxxxxx-000-000-101", "aflojó (se)",       "aflojó (se).png",       "v.t.pret."),
("v.i.pres.xxxxxx-000-000-102", "agacha (se)",       "agacha (se).png",       "v.i.pres."),
("v.i.xxxxxxxxxxx-000-000-103", "agacharse",         "agacharse.png",         "v.i."),
("v.t.pres.xxxxxx-000-000-104", "agarra",            "agarra.png",            "v.t.pres."),
("adj.xxxxxxxxxxx-000-000-105", "agarrado,a",        "agarrado,a.png",        "adj."),
("v.t. imper.xxxx-000-000-106", "agárralo",          "agárralo.png",          "v.t. imper."),
("v.t.compl.xxxxx-000-000-107", "agarrar (fue a)",   "agarrar (fue a).png",   "v.t.compl."),
("v.t.compl.xxxxx-000-000-108", "agarrar (vino a)",  "agarrar (vino a).png",  "v.t.compl."),
("v.t.fut.xxxxxxx-000-000-109", "agarrará",          "agarrará.png",          "v.t.fut."),
("v.t.pospr.xxxxx-000-000-110", "agarraría",         "agarraría.png",         "v.t.pospr."),
("v.t.pret.xxxxxx-000-000-111", "agarró (lo)",       "agarró (lo).png",       "v.t.pret."),
("v.t.pret.xxxxxx-000-000-112", "agarró",            "agarró.png",            "v.t.pret."),
("adj.xxxxxxxxxxx-000-000-113", "agrio,a",           "agrio,a.png",           "adj."),
("s.xxxxxxxxxxxxx-000-000-114", "agua",              "agua.png",              "s."),
("s.xxxxxxxxxxxxx-000-000-115", "agua salada",       "agua salada.png",       "s."),
("s.xxxxxxxxxxxxx-000-000-116", "agua limpia",       "agua limpia.png",       "s."),
("s.xxxxxxxxxxxxx-000-000-117", "agua hervida",      "agua hervida.png",      "s."),
("s.xxxxxxxxxxxxx-000-000-118", "agua fría",         "agua fría.png",         "s."),
("s.xxxxxxxxxxxxx-000-000-119", "agua estancada",    "agua estancada.png",    "s."),
("s.xxxxxxxxxxxxx-000-000-120", "agua dulce",        "agua dulce.png",        "s."),
("s.xxxxxxxxxxxxx-000-000-121", "agua de chile",     "agua de chile.png",     "s.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.60
("v.i.copr.xxxxxx-000-000-122", "bailaba",               "bailaba.png",               "v.i.copr."),
("adj.xxxxxxxxxxx-000-000-123", "bailador,a",            "bailador,a.png",            "adj."),
("v.i.ger.compl.x-000-000-124", "bailando,está",         "bailando,está.png",         "v.i.ger.compl."),
("v.i.fut.xxxxxxx-000-000-125", "bailará",               "bailará.png",               "v.i.fut."),
("v.i.pospr.xxxxx-000-000-126", "bailaría",              "bailaría.png",              "v.i.pospr."),
("s.xxxxxxxxxxxxx-000-000-127", "baile",                 "baile.png",                 "s."),
("v.i.pret.xxxxxx-000-000-128", "bailó",                 "bailó.png",                 "v.i.pret."),
("v.i.pret.xxxxxx-000-000-129", "baja",                  "baja.png",                  "v.i.pret."),
("v.t.imper.xxxxx-000-000-130", "bájale",                "bájale.png",                "v.t.imper."),
("v.i.pres.xxxxxx-000-000-131", "bajamos",               "bajamos.png",               "v.i.pres."),
("v.i.v.t.xxxxxxx-000-000-132", "bajar",                 "bajar.png",                 "v.i.v.t."),
("v.i.pret.xxxxxx-000-000-133", "bajaron",               "bajaron.png",               "v.i.pret."),
("v.i.imper.xxxxx-000-000-134", "bajen",                 "bajen.png",                 "v.i.imper."),
("adj.xxxxxxxxxxx-000-000-135", "bajo,a",                "bajo,a.png",                "adj."),
("adj.prep.xxxxxx-000-000-136", "bajo (el agua)",        "bajo (el agua).png",        "adj.prep."),
("v.i.pres.xxxxxx-000-000-137", "baña (se) en temascal", "baña (se) en temascal.png", "v.i.pres."),
("v.i.v.t.pres.xx-000-000-138", "baña",                  "baña.png",                  "v.i.v.t.pres."),
("v.i.imper.xxxxx-000-000-139", "báñate",                "báñate.png",                "v.i.imper."),
("v.i.imper.rev.x-000-000-140", "bañese usted",          "bañese usted.png",          "v.i.imper.rev."),
("s.xxxxxxxxxxxxx-000-000-141", "baño de vapor",         "baño de vapor.png",         "s."),
("adj.xxxxxxxxxxx-000-000-142", "barato,a",              "barato,a.png",              "adj."),
("s.xxxxxxxxxxxxx-000-000-143", "barba",                 "barba.png",                 "s."),
("s.xxxxxxxxxxxxx-000-000-144", "barba (de ocote)",      "barba (de ocote).png",      "s."),
("s.xxxxxxxxxxxxx-000-000-145", "barbilla",              "barbilla.png",              "s."),
("s.xxxxxxxxxxxxx-000-000-146", "barco,a",               "barco,a.png",               "s."),
("s.xxxxxxxxxxxxx-000-000-147", "barranca,o",            "barranca,o.png",            "s."),
("s.xxxxxxxxxxxxx-000-000-148", "barranquilla",          "barranquilla.png",          "s."),
("v.t.xxxxxxxxxxx-000-000-149", "barre",                 "barre.png",                 "v.t."),
("adj.xxxxxxxxxxx-000-000-150", "barredor,a",            "barredor,a.png",            "adj."),
("v.t.xxxxxxxxxxx-000-000-151", "barrer",                "barrer.png",                "v.t."),
("v.t.fut.xxxxxxx-000-000-152", "barrerá",               "barrerá.png",               "v.t.fut."),
("v.t.copr.xxxxxx-000-000-153", "barría",                "barría.png",                "v.t.copr."),
("adj.xxxxxxxxxxx-000-000-154", "barrido,a",             "barrido,a.png",             "adj."),
("s.xxxxxxxxxxxxx-000-000-155", "barriga",               "barriga.png",               "s."),
("s.xxxxxxxxxxxxx-000-000-156", "barrio",                "barrio.png",                "s."),
("v.t.pospr.xxxxx-000-000-157", "barriría",              "barriría.png",              "v.t.pospr."),
("s.xxxxxxxxxxxxx-000-000-158", "basura",                "basura.png",                "s."),
("v.t.xxxxxxxxxxx-000-000-159", "batir",                 "batir.png",                 "v.t."),
("v.t.fut.xxxxxxx-000-000-160", "batirá",                "batirá.png",                "v.t.fut."),
("v.t.imper.xxxxx-000-000-161", "bautícelo",             "bautícelo.png",             "v.t.imper."),
("s.v.t.pret.xxxx-000-000-162", "bautizó",               "bautizó.png",               "s.v.t.pret."),
("v.t.imper.xxxxx-000-000-163", "beba (agua)",           "beba (agua).png",           "v.t.imper."),
("compl.rev.xxxxx-000-000-164", "beba (usted)",          "beba (usted).png",          "compl.rev."),
("v.i.imper.xxxxx-000-000-165", "beba (lo) usted",       "beba (lo) usted.png",       "v.i.imper.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.61
("v.t.pres.xxxxxx-000-000-166", "bebe (agua)",             "bebe (agua).png",             "v.t.pres."),
("v.t.pres.xxxxxx-000-000-167", "bebe (agua)",             "bebe (agua).png",             "v.t.pres."),
("v.t.pres.xxxxxx-000-000-168", "bebe",                    "bebe.png",                    "v.t.pres."),
("v.t.imper.xxxxx-000-000-169", "bebelo",                  "bebelo.png",                  "v.t.imper."),
("v.t.xxxxxxxxxxx-000-000-170", "beber",                   "beber.png",                   "v.t."),
("v.t.xxxxxxxxxxx-000-000-171", "beber (sin cuchara)",     "beber (sin cuchara).png",     "v.t."),
("v.t.fut.xxxxxxx-000-000-172", "beberá",                  "beberá.png",                  "v.t.fut."),
("v.t.pospre.xxxx-000-000-173", "bebería",                 "bebería.png",                 "v.t.pospre."),
("v.t.pret.xxxxxx-000-000-174", "bebí (lo)",               "bebí (lo).png",               "v.t.pret."),
("v.t.xxxxxxxxxxx-000-000-175", "bebía (agua)",            "bebía (agua).png",            "v.t."),
("v.t.copre.xxxxx-000-000-176", "bebía",                   "bebía.png",                   "v.t.copre."),
("v.t.ger.xxxxxxx-000-000-177", "bebiendo (agua)",         "bebiendo (agua).png",         "v.t.ger."),
("v.t.ger.xxxxxxx-000-000-178", "bebiendo",                "bebiendo.png",                "v.t.ger."),
("v.t.pret.xxxxxx-000-000-179", "bebió (agua)",            "bebió (agua).png",            "v.t.pret."),
("v.t.pret.xxxxxx-000-000-180", "bebió",                   "bebió.png",                   "v.t.pret."),
("v.t.pres.xxxxxx-000-000-181", "bebo",                    "bebo.png",                    "v.t.pres."),
("s.xxxxxxxxxxxxx-000-000-182", "bejuco",                  "bejuco.png",                  "s."),
("s.xxxxxxxxxxxxx-000-000-183", "bellota",                 "bellota.png",                 "s."),
("s.xxxxxxxxxxxxx-000-000-184", "bellota",                 "bellota.png",                 "s."),
("s.xxxxxxxxxxxxx-000-000-185", "berrinche",               "berrinche.png",               "s."),
("s.xxxxxxxxxxxxx-000-000-186", "berro",                   "berro.png",                   "s."),
("s.xxxxxxxxxxxxx-000-000-187", "biblioteca",              "biblioteca.png",              "s."),
("s.xxxxxxxxxxxxx-000-000-188", "bíceps",                  "bíceps.png",                  "s."),
("s.xxxxxxxxxxxxx-000-000-189", "bien",                    "bien.png",                    "s."),
("adv.xxxxxxxxxxx-000-000-190", "bien",                    "bien.png",                    "adv."),
("s.xxxxxxxxxxxxx-000-000-191", "bifurcación",             "bifurcación.png",             "s."),
("s.xxxxxxxxxxxxx-000-000-192", "bigote",                  "bigote.png",                  "s."),
("adj.xxxxxxxxxxx-000-000-193", "bigotón",                 "bigotón.png",                 "adj."),
("s.xxxxxxxxxxxxx-000-000-194", "bilis",                   "bilis.png",                   "s."),
("s.xxxxxxxxxxxxx-000-000-195", "billete",                 "billete.png",                 "s."),
("adj.xxxxxxxxxxx-000-000-196", "blanco,a",                "blanco,a.png",                "adj."),
("s.adj.xxxxxxxxx-000-000-197", "blancos,a",               "blancos,a.png",               "s.adj."),
("s.xxxxxxxxxxxxx-000-000-198", "blancura",                "blancura.png",                "s."),
("s.xxxxxxxxxxxxx-000-000-199", "blusa",                   "blusa.png",                   "s."),
("s.xxxxxxxxxxxxx-000-000-200", "boca (amarga)",           "boca (amarga).png",           "s."),
("s.xxxxxxxxxxxxx-000-000-201", "boca (angosta), boquita", "boca (angosta), boquita.png", "s."),
("s.xxxxxxxxxxxxx-000-000-202", "boca (apestosa)",         "boca (apestosa).png",         "s."),
("s.xxxxxxxxxxxxx-000-000-203", "boca (grande), bocota",   "boca (grande), bocota.png",   "s."),
("s.xxxxxxxxxxxxx-000-000-204", "boca (olorosa)",          "boca (olorosa).png",          "s."),
("s.xxxxxxxxxxxxx-000-000-205", "boca",                    "boca.png",                    "s."),
("adj.xxxxxxxxxxx-000-000-206", "bocabajo",                "bocabajo.png",                "adj."),
("s.xxxxxxxxxxxxx-000-000-207", "boda",                    "boda.png",                    "s."),
("s.xxxxxxxxxxxxx-000-000-208", "bola",                    "bola.png",                    "s."),
("s.xxxxxxxxxxxxx-000-000-209", "bolsa",                   "bolsa.png",                   "s.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.62
("adj.xxxxxxxxxxx-000-000-210", "bonito,a",               "bonito,a.png",               "adj."),
("adj.xxxxxxxxxxx-000-000-211", "bonito,a",               "bonito,a.png",               "adj."),
("s.rev.xxxxxxxxx-000-000-212", "boquita",                "boquita.png",                "s.rev."),
("v.t.xxxxxxxxxxx-000-000-213", "borrar, perdonar",       "borrar, perdonar.png",       "v.t."),
("s.xxxxxxxxxxxxx-000-000-214", "borrego",                "borrego.png",                "s."),
("s.xxxxxxxxxxxxx-000-000-215", "borregos",               "borregos.png",               "s."),
("s.rev.xxxxxxxxx-000-000-216", "borreguito,a",           "borreguito,a.png",           "s.rev."),
("s.xxxxxxxxxxxxx-000-000-217", "bosteza",                "bosteza.png",                "s."),
("v.i.ger.xxxxxxx-000-000-218", "bostezando",             "bostezando.png",             "v.i.ger."),
("v.i.xxxxxxxxxxx-000-000-219", "bostezar",               "bostezar.png",               "v.i."),
("v.i.fut.xxxxxxx-000-000-220", "bostezará",              "bostezará.png",              "v.i.fut."),
("v.i.pret.xxxxxx-000-000-221", "bostezó",                "bostezó.png",                "v.i.pret."),
("s.xxxxxxxxxxxxx-000-000-222", "botella",                "botella.png",                "s."),
("s.xxxxxxxxxxxxx-000-000-223", "botella (de vino)",      "botella (de vino).png",      "s."),
("s.xxxxxxxxxxxxx-000-000-224", "brasa",                  "brasa.png",                  "s."),
("s.xxxxxxxxxxxxx-000-000-225", "brasero",                "brasero.png",                "s."),
("*.xxxxxxxxxxxxx-000-000-226", "bravo, corretea",        "bravo, corretea.png",        "*."),
("s.xxxxxxxxxxxxx-000-000-227", "brazo (torcido)",        "brazo (torcido).png",        "s."),
("s.xxxxxxxxxxxxx-000-000-228", "brazo",                  "brazo.png",                  "s."),
("v.i.xxxxxxxxxxx-000-000-229", "brillar,centellear",     "brillar,centellear.png",     "v.i."),
("adj.xxxxxxxxxxx-000-000-230", "brilloso,a (brillante)", "brilloso,a (brillante).png", "adj."),
("*.xxxxxxxxxxxxx-000-000-231", "brinca",                 "brinca.png",                 "*."),
("v.t.fut.xxxxxxx-000-000-232", "brincará",               "brincará.png",               "v.t.fut."),
("v.t.pret.xxxxxx-000-000-233", "brincó",                 "brincó.png",                 "v.t.pret."),
("s.xxxxxxxxxxxxx-000-000-234", "brisa",                  "brisa.png",                  "s."),
("v.i.xxxxxxxxxxx-000-000-235", "brota",                  "brota.png",                  "v.i."),
("s.xxxxxxxxxxxxx-000-000-236", "pres brujo",             "pres brujo.png",             "s."),
("adj.compl.xxxxx-000-000-237", "buen día",               "buen día.png",               "adj.compl."),
("compl.xxxxxxxxx-000-000-238", "buena tarde",            "buena tarde.png",            "compl."),
("compl.xxxxxxxxx-000-000-239", "buenas tardes plural",   "buenas tardes plural.png",   "compl."),
("adv.xxxxxxxxxxx-000-000-240", "bueno,a",                "bueno,a.png",                "adv."),
("compl.xxxxxxxxx-000-000-241", "buenos días (plural)",   "buenos días (plural).png",   "compl."),
("s.xxxxxxxxxxxxx-000-000-242", "búho",                   "búho.png",                   "s."),
("s.xxxxxxxxxxxxx-000-000-243", "bule de agua",           "bule de agua.png",           "s."),
("v.i.pres.xxxxxx-000-000-244", "burbujea",               "burbujea.png",               "v.i.pres."),
("adj.xxxxxxxxxxx-000-000-245", "burlador,a",             "burlador,a.png",             "adj."),
("s.xxxxxxxxxxxxx-000-000-246", "burra",                  "burra.png",                  "s."),
("s.xxxxxxxxxxxxx-000-000-247", "burrito",                "burrito.png",                "s."),
("v.t.pres.xxxxxx-000-000-248", "busca",                  "busca.png",                  "v.t.pres."),
("v.t.xxxxxxxxxxx-000-000-249", "búscale",                "búscale.png",                "v.t."),
("v.t.xxxxxxxxxxx-000-000-240", "buscar",                 "buscar.png",                 "v.t."),
("v.t.pres.xxxxxx-000-000-251", "busco",                  "busco.png",                  "v.t.pres."),
("s.xxxxxxxxxxxxx-000-000-252", "caballo",                "caballo.png",                "s."),
("v.i.xxxxxxxxxxx-000-000-253", "cabecea",                "cabecea.png",                "v.i.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.63
("v.t.xxxxxxxxxxx-000-000-254", "cabecear (sacudir la cabeza)",          "cabecear (sacudir la cabeza).png",           "v.t."),
("s.xxxxxxxxxxxxx-000-000-255", "cabecera",                              "cabecera.png",                               "s."),
("s.xxxxxxxxxxxxx-000-000-256", "cabellera",                             "cabellera.png",                              "s."),
("s.xxxxxxxxxxxxx-000-000-257", "cabello, pelo",                         "cabello, pelo.png",                          "s."),
("s.xxxxxxxxxxxxx-000-000-258", "cabello de jilote",                     "cabello de jilote.png",                      "s."),
("s.xxxxxxxxxxxxx-000-000-259", "cabello largo",                         "cabello largo.png",                          "s."),
("s.xxxxxxxxxxxxx-000-000-260", "cabeza",                                "cabeza.png",                                 "s."),
("s.xxxxxxxxxxxxx-000-000-261", "cabeza con canas",                      "cabeza con canas.png",                       "s."),
("s.xxxxxxxxxxxxx-000-000-262", "cacahuate",                             "cacahuate.png",                              "s."),
("s.xxxxxxxxxxxxx-000-000-263", "cacao",                                 "cacao.png",                                  "s."),
("s.xxxxxxxxxxxxx-000-000-264", "cacomistle",                            "cacomistle.png",                             "s."),
("s.xxxxxxxxxxxxx-000-000-265", "cactus",                                "cactus.png",                                 "s."),
("compl.xxxxxxxxx-000-000-266", "cada tercer dia",                       "cada tercer dia.png",                        "compl."),
("v.i.pres.xxxxxx-000-000-267", "cae",                                   "cae.png",                                    "v.i.pres."),
("v.i.pres.xxxxxx-000-000-268", "cae (agua)",                            "cae (agua).png",                             "v.i.pres."),
("v.i.pres.xxxxxx-000-000-269", "cae (se)",                              "cae (se).png",                               "v.i.pres."),
("v.i.pres.compl.-000-000-270", "cae el cabello",                        "cae el cabello.png",                         "v.i.pres.compl."),
("v.i.compl.xxxxx-000-000-271", "caer (fue a)",                          "caer (fue a).png",                           "v.i.compl."),
("v.i.compl.xxxxx-000-000-272", "caer (vino a)",                         "caer (vino a).png",                          "v.i.compl."),
("v.i.fut.xxxxxxx-000-000-273", "caerá",                                 "caerá.png",                                  "v.i.fut."),
("v.i.fut.rev.xxx-000-000-274", "caerá",                                 "caerá.png",                                  "v.i.fut.rev."),
("v.t.fut.xxxxxxx-000-000-275", "caerás",                                "caerás.png",                                 "v.t.fut."),
("v.i.pospr.xxxxx-000-000-276", "caería (se)",                           "caería (se).png",                            "v.i.pospr."),
("s.xxxxxxxxxxxxx-000-000-277", "café",                                  "café.png",                                   "s."),
("s.rev.xxxxxxxxx-000-000-278", "cafecito",                              "cafecito.png",                               "s.rev."),
("s.xxxxxxxxxxxxx-000-000-279", "caída de pelo",                         "caída de pelo.png",                          "s."),
("adj.xxxxxxxxxxx-000-000-280", "caído,a tirado,a",                      "caído,a tirado,a.png",                       "adj."),
("s.xxxxxxxxxxxxx-000-000-281", "cal",                                   "cal.png",                                    "s."),
("s.xxxxxxxxxxxxx-000-000-282", "calabacitas",                           "calabacitas.png",                            "s."),
("s.xxxxxxxxxxxxx-000-000-283", "calabaza (hervida)",                    "calabaza (hervida).png",                     "s."),
("s.xxxxxxxxxxxxx-000-000-284", "calabaza (tierna)",                     "calabaza (tierna).png",                      "s."),
("s.xxxxxxxxxxxxx-000-000-285", "calabaza",                              "calabaza.png",                               "s."),
("s.xxxxxxxxxxxxx-000-000-286", "calabazo (para llevar agua, tecomate)", "calabazo (para llevar agua, tecomate).png",  "s."),
("s.xxxxxxxxxxxxx-000-000-287", "calambres",                             "calambres.png",                              "s."),
("s.xxxxxxxxxxxxx-000-000-288", "calendario",                            "calendario.png",                             "s."),
("v.i.xxxxxxxxxxx-000-000-289", "calentar (se)",                         "calentar (se).png",                          "v.i."),
("s.xxxxxxxxxxxxx-000-000-290", "calentura",                             "calentura.png",                              "s."),
("s.xxxxxxxxxxxxx-000-000-291", "calentura de aires",                    "calentura de aires.png",                     "s."),
("v.t.pres.xxxxxx-000-000-292", "calienta",                              "calienta.png",                               "v.t.pres."),
("v.t.imper.xxxxx-000-000-293", "caliéntalo",                            "caliéntalo.png",                             "v.t.imper."),
("adj.xxxxxxxxxxx-000-000-294", "caliente",                              "caliente.png",                               "adj."),
("v.i.imper.xxxxx-000-000-295", "cállate",                               "cállate.png",                                "v.i.imper."),
("s.xxxxxxxxxxxxx-000-000-296", "calor (en el estómago)",                "calor (en el estómago).png",                 "s."),
("s.xxxxxxxxxxxxx-000-000-297", "calor (en la boca)",                    "calor (en la boca).png",                     "s.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.64
("s.xxxxxxxxxxxxx-000-000-298", "calor por envidia",       "calor por envidia.png",       "s."),
("s.xxxxxxxxxxxxx-000-000-299", "calor",                   "calor.png",                   "s."),
("s.xxxxxxxxxxxxx-000-000-300", "calosfríos",              "calosfríos.png",              "s."),
("s.xxxxxxxxxxxxx-000-000-301", "calzón",                  "calzón.png",                  "s."),
("s.xxxxxxxxxxxxx-000-000-302", "calzado (de fibra)",      "calzado (de fibra).png",      "s."),
("s.xxxxxxxxxxxxx-000-000-303", "calzado",                 "calzado.png",                 "s."),
("s.xxxxxxxxxxxxx-000-000-304", "cama",                    "cama.png",                    "s."),
("v.i.pres.xxxxxx-000-000-305", "cambia (de dientes)",     "cambia (de dientes).png",     "v.i.pres."),
("v.i.pres.compl.-000-000-306", "cambia de ropa",          "cambia de ropa.png",          "v.i.pres.compl."),
("v.i.pres.imper.-000-000-307", "cambiamos",               "cambiamos.png",               "v.i.pres.imper."),
("v.t.v.i.xxxxxxx-000-000-308", "cambiar",                 "cambiar.png",                 "v.t.v.i."),
("v.i.xxxxxxxxxxx-000-000-309", "cambiar (se) de ropa",    "cambiar (se) de ropa.png",    "v.i."),
("s.xxxxxxxxxxxxx-000-000-310", "cambio de dientes",       "cambio de dientes.png",       "s."),
("v.i.pres.xxxxxx-000-000-311", "camina",                  "camina.png",                  "v.i.pres."),
("v.i.pres.xxxxxx-000-000-312", "camina",                  "camina.png",                  "v.i.pres."),
("v.i.copr.xxxxxx-000-000-313", "caminaba",                "caminaba.png",                "v.i.copr."),
("v.i.ger.xxxxxxx-000-000-314", "caminando (está)",        "caminando (está).png",        "v.i.ger."),
("v.i.ger.xxxxxxx-000-000-315", "caminando",               "caminando.png",               "v.i.ger."),
("s.adj.xxxxxxxxx-000-000-316", "caminantes",              "caminantes.png",              "s.adj."),
("v.i.fut.compl.x-000-000-317", "caminar (iráa)",          "caminar (iráa).png",          "v.i.fut.compl."),
("v.i.fut.xxxxxxx-000-000-318", "caminará",                "caminará.png",                "v.i.fut."),
("v.i.fut.xxxxxxx-000-000-319", "caminarán",               "caminarán.png",               "v.i.fut."),
("v.i.copr.xxxxxx-000-000-320", "caminaría",               "caminaría.png",               "v.i.copr."),
("v.i.pret.xxxxxx-000-000-321", "caminó",                  "caminó.png",                  "v.i.pret."),
("s.xxxxxxxxxxxxx-000-000-322", "camino estrecho",         "camino estrecho.png",         "s."),
("s.xxxxxxxxxxxxx-000-000-323", "camino",                  "camino.png",                  "s."),
("s.xxxxxxxxxxxxx-000-000-324", "camisa",                  "camisa.png",                  "s."),
("s.xxxxxxxxxxxxx-000-000-325", "camote (de chayote)",     "camote (de chayote).png",     "s."),
("s.xxxxxxxxxxxxx-000-000-326", "camote",                  "camote.png",                  "s."),
("s.xxxxxxxxxxxxx-000-000-327", "canal (deagua)",          "canal (deagua).png",          "s."),
("s.xxxxxxxxxxxxx-000-000-328", "canasta para tortillas",  "canasta para tortillas.png",  "s."),
("s.xxxxxxxxxxxxx-000-000-329", "canasta",                 "canasta.png",                 "s."),
("s.xxxxxxxxxxxxx-000-000-330", "cansancio",               "cansancio.png",               "s."),
("s.xxxxxxxxxxxxx-000-000-331", "cansancio (reverencial)", "cansancio (reverencial).png", "s."),
("v.i.pret.xxxxxx-000-000-332", "cansaron (se)",           "cansaron (se).png",           "v.i.pret."),
("v.t.pres.xxxxxx-000-000-333", "canta",                   "canta.png",                   "v.t.pres."),
("v.i.ger.xxxxxxx-000-000-334", "cantando (está)",         "cantando (está).png",         "v.i.ger."),
("s.adj.xxxxxxxxx-000-000-335", "cantante",                "cantante.png",                "s.adj."),
("s.adj.xxxxxxxxx-000-000-336", "cantante religioso,a",    "cantante religioso,a.png",    "s.adj."),
("v.i.vt.xxxxxxxx-000-000-337", "cantar",                  "cantar.png",                  "v.i.vt."),
("v.i.fut.xxxxxxx-000-000-338", "cantará",                 "cantará.png",                 "v.i.fut."),
("v.t.fut.xxxxxxx-000-000-339", "cantaremos alabanzas",    "cantaremos alabanzas.png",    "v.t.fut."),
("*.xxxxxxxxxxxxx-000-000-340", "cántaro",                 "cántaro.png",                 "*."),
("*.xxxxxxxxxxxxx-000-000-341", "cántaro (de barro)",      "cántaro (de barro).png",      "*.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.65
("*.xxxxxxxxxxxxx-000-000-342", "cante usted",             "cante usted.png",                 "*."),
("v.t.pret.xxxxxx-000-000-343", "cantó",                   "cantó.png",                       "v.t.pret."),
("s.xxxxxxxxxxxxx-000-000-344", "canto",                   "canto.png",                       "s."),
("v.t.pret.xxxxxx-000-000-345", "cantó usted",             "cantó usted.png",                 "v.t.pret."),
("s.xxxxxxxxxxxxx-000-000-346", "canto, poesía",           "canto, poesía.png",               "s."),
("adj.xxxxxxxxxxx-000-000-347", "cantor,a",                "cantor,a.png",                    "adj."),
("s.xxxxxxxxxxxxx-000-000-348", "caña",                    "caña.png",                        "s."),
("v.t.xxxxxxxxxxx-000-000-349", "capar",                   "capar.png",                       "v.t."),
("s.xxxxxxxxxxxxx-000-000-350", "capulín medicinal",       "capulín medicinal.png",           "s."),
("s.xxxxxxxxxxxxx-000-000-351", "capulín",                 "capulín.png",                     "s."),
("s.xxxxxxxxxxxxx-000-000-352", "cara del sol",            "cara del sol.png",                "s."),
("s.xxxxxxxxxxxxx-000-000-353", "cara, rostro",            "cara, rostro.png",                "s."),
("s.xxxxxxxxxxxxx-000-000-354", "carbón",                  "carbón.png",                      "s."),
("v.t.pres.xxxxxx-000-000-355", "carcajea",                "carcajea.png",                    "v.t.pres."),
("v.t.xxxxxxxxxxx-000-000-356", "cardar",                  "cardar.png",                      "v.t."),
("s.xxxxxxxxxxxxx-000-000-357", "cardar (la lana)",        "cardar (la lana).png",            "s."),
("v.t.imper.xxxxx-000-000-358", "cárgalo",                 "cárgalo.png",                     "v.t.imper."),
("v.t.imper.xxxxx-000-000-359", "cárgalo",                 "cárgalo.png",                     "v.t.imper."),
("v.t.xxxxxxxxxxx-000-000-360", "cargar (en brazos)",      "cargar (en brazos).png",          "v.t."),
("v.t.pret.xxxxxx-000-000-361", "cargó (lo)",              "cargó (lo).png",                  "v.t.pret."),
("s.xxxxxxxxxxxxx-000-000-362", "cariño",                  "cariño.png",                      "s."),
("s.xxxxxxxxxxxxx-000-000-363", "carne (de chivo)",        "carne (de chivo).png",            "s."),
("s.xxxxxxxxxxxxx-000-000-364", "carne (seca)",            "carne (seca).png",                "s."),
("s.compl.xxxxxxx-000-000-365", "carne (tu)",              "carne (tu).png",                  "s.compl."),
("s.xxxxxxxxxxxxx-000-000-366", "carne de pollo",          "carne de pollo.png",              "s."),
("s.xxxxxxxxxxxxx-000-000-367", "carne de puerco",         "carne de puerco.png",             "s."),
("s.xxxxxxxxxxxxx-000-000-368", "carne de res",            "carne de res.png",                "s."),
("s.xxxxxxxxxxxxx-000-000-369", "carne",                   "carne.png",                       "s."),
("*.xxxxxxxxxxxxx-000-000-370", "carnicero",               "carnicero.png",                   "*."),
("adj.xxxxxxxxxxx-000-000-371", "carnudo,a",               "carnudo,a.png",                   "adj."),
("adj.xxxxxxxxxxx-000-000-372", "caro,a",                  "caro,a.png",                      "adj."),
("adj.xxxxxxxxxxx-000-000-373", "caros,as",                "caros,as.png",                    "adj."),
("s.xxxxxxxxxxxxx-000-000-374", "carrizo",                 "carrizo.png",                     "s."),
("s.xxxxxxxxxxxxx-000-000-375", "casa (abierta)",          "casa (abierta).png",              "s."),
("s.xxxxxxxxxxxxx-000-000-376", "casa (cerrada)",          "casa (cerrada).png",              "s."),
("s.xxxxxxxxxxxxx-000-000-377", "casa (de- )",             "casa (de- ).png",                 "s."),
("s.xxxxxxxxxxxxx-000-000-378", "casa (de enfermos)",      "casa (de enfermos).png",          "s."),
("rev.s.xxxxxxxxx-000-000-379", "casa (de ustedes)",       "casa (de ustedes).png",           "rev.s."),
("rev.xxxxxxxxxxx-000-000-380", "casa (la, de usted)comp", "casa (la, de usted)comp.png",     "rev."),
("s.compl.xxxxxxx-000-000-381", "casa (mi)",               "casa (mi).png",                   "s.compl."),
("s.xxxxxxxxxxxxx-000-000-382", "casa (reverencial)",      "casa (reverencial).png",          "s."),
("s.compl.xxxxxxx-000-000-383", "casa (tu)",               "casa (tu).png",                   "s.compl."),
("s.xxxxxxxxxxxxx-000-000-384", "casa de piedra",          "casa de piedra.png",              "s."),
("s.xxxxxxxxxxxxx-000-000-385", "casa",                    "casa.png",                        "s.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.66
("s.xxxxxxxxxxxxx-000-000-386", "casas (de ustedes)",        "casas (de ustedes).png",        "s."),
("s.xxxxxxxxxxxxx-000-000-387", "casas",                     "casas.png",                     "s."),
("v.t.pres.xxxxxx-000-000-388", "cascabelea",                "cascabelea.png",                "v.t.pres."),
("s.xxxxxxxxxxxxx-000-000-389", "cascada",                   "cascada.png",                   "s."),
("s.xxxxxxxxxxxxx-000-000-390", "cáscara",                   "cáscara.png",                   "s."),
("v.i.pres.xxxxxx-000-000-391", "caso (me, hombre)",         "caso (me, hombre).png",         "v.i.pres."),
("v.i.xxxxxxxxxxx-000-000-392", "caso (me, mujer)",          "caso (me, mujer).png",          "v.i."),
("s.xxxxxxxxxxxxx-000-000-393", "caspa",                     "caspa.png",                     "s."),
("s.xxxxxxxxxxxxx-000-000-394", "catarro",                   "catarro.png",                   "s."),
("v.t.xxxxxxxxxxx-000-000-395", "cavar, escarbar",           "cavar, escarbar.png",           "v.t."),
("v.i.ger.xxxxxxx-000-000-396", "cayendo",                   "cayendo.png",                   "v.i.ger."),
("v.i.pret.xxxxxx-000-000-397", "cayó (se)",                 "cayó (se).png",                 "v.i.pret."),
("v.i.rev.xxxxxxx-000-000-398", "cayó (se)",                 "cayó (se).png",                 "v.i.rev."),
("s.xxxxxxxxxxxxx-000-000-399", "cazuela",                   "cazuela.png",                   "s."),
("s.xxxxxxxxxxxxx-000-000-400", "cebolla",                   "cebolla.png",                   "s."),
("s.xxxxxxxxxxxxx-000-000-401", "ceguera",                   "ceguera.png",                   "s."),
("*.xxxxxxxxxxxxx-000-000-402", "ceiba, pochote",            "ceiba, pochote.png",            "*."),
("s.xxxxxxxxxxxxx-000-000-403", "ceja",                      "ceja.png",                      "s."),
("s.xxxxxxxxxxxxx-000-000-404", "cejas (largas)",            "cejas (largas).png",            "s."),
("s.xxxxxxxxxxxxx-000-000-405", "cejas",                     "cejas.png",                     "s."),
("s.xxxxxxxxxxxxx-000-000-406", "ceniza",                    "ceniza.png",                    "s."),
("s.xxxxxxxxxxxxx-000-000-407", "ceniza",                    "ceniza.png",                    "s."),
("adj.xxxxxxxxxxx-000-000-408", "cenizo,a",                  "cenizo,a.png",                  "adj."),
("s.xxxxxxxxxxxxx-000-000-409", "centro, en medio",          "centro, en medio.png",          "s."),
("adv.xxxxxxxxxxx-000-000-410", "cerca",                     "cerca.png",                     "adv."),
("s.xxxxxxxxxxxxx-000-000-411", "cerca",                     "cerca.png",                     "s."),
("s.xxxxxxxxxxxxx-000-000-412", "cerdo",                     "cerdo.png",                     "s."),
("s.xxxxxxxxxxxxx-000-000-413", "cerdos",                    "cerdos.png",                    "s."),
("s.xxxxxxxxxxxxx-000-000-414", "cerilla (de oídos)",        "cerilla (de oídos).png",        "s."),
("s.xxxxxxxxxxxxx-000-000-415", "cerilla (en los oídos)",    "cerilla (en los oídos).png",    "s."),
("adj.xxxxxxxxxxx-000-000-416", "cerrado,a",                 "cerrado,a.png",                 "adj."),
("v.t.xxxxxxxxxxx-000-000-417", "cerrar",                    "cerrar.png",                    "v.t."),
("v.t.xxxxxxxxxxx-000-000-418", "cerrar",                    "cerrar.png",                    "v.t."),
("v.t.xxxxxxxxxxx-000-000-419", "cerrar (los ojos)",         "cerrar (los ojos).png",         "v.t."),
("v.t.xxxxxxxxxxx-000-000-420", "cerrar muñeca, hacer puño", "cerrar muñeca, hacer puño.png", "v.t."),
("*.xxxxxxxxxxxxx-000-000-421", "cerro",                     "cerro.png",                     "*."),
("*.xxxxxxxxxxxxx-000-000-422", "cerró",                     "cerró.png",                     "*."),
("s.xxxxxxxxxxxxx-000-000-423", "cerro (de Hueyapan)",       "cerro (de Hueyapan).png",       "s."),
("s.xxxxxxxxxxxxx-000-000-424", "cerro (del guaje)",         "cerro (del guaje).png",         "s."),
("s.xxxxxxxxxxxxx-000-000-425", "cerro que humea",           "cerro que humea.png",           "s."),
("s.xxxxxxxxxxxxx-000-000-426", "chachalaca",                "chachalaca.png",                "s."),
("s.xxxxxxxxxxxxx-000-000-427", "chalcatsingo",              "chalcatsingo.png",              "s."),
("s.xxxxxxxxxxxxx-000-000-428", "chapulines",                "chapulines.png",                "s."),
("s.xxxxxxxxxxxxx-000-000-429", "chayote (hervido)",         "chayote (hervido).png",         "s.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.67
("s.xxxxxxxxxxxxx-000-000-430", "chayote (tierno)",              "chayote (tierno).png",              "s."),
("s.xxxxxxxxxxxxx-000-000-431", "chayote",                       "chayote.png",                       "s."),
("s.rev.xxxxxxxxx-000-000-432", "chayotillo",                    "chayotillo.png",                    "s.rev."),
("s.xxxxxxxxxxxxx-000-000-433", "chicalote",                     "chicalote.png",                     "s."),
("s.xxxxxxxxxxxxx-000-000-434", "chicle",                        "chicle.png",                        "s."),
("adj.xxxxxxxxxxx-000-000-435", "chicloso,a",                    "chicloso,a.png",                    "adj."),
("s.xxxxxxxxxxxxx-000-000-436", "chicomóstoc",                   "chicomóstoc.png",                   "s."),
("s.xxxxxxxxxxxxx-000-000-437", "chilaquil",                     "chilaquil.png",                     "s."),
("s.xxxxxxxxxxxxx-000-000-438", "chile (pequeño)",               "chile (pequeño).png",               "s."),
("s.xxxxxxxxxxxxx-000-000-439", "chile (seco)",                  "chile (seco).png",                  "s."),
("s.xxxxxxxxxxxxx-000-000-440", "chile",                         "chile.png",                         "s."),
("s.rev.xxxxxxxxx-000-000-441", "chilito",                       "chilito.png",                       "s.rev."),
("s.xxxxxxxxxxxxx-000-000-442", "chincuete",                     "chincuete.png",                     "s."),
("s.xxxxxxxxxxxxx-000-000-443", "chipil",                        "chipil.png",                        "s."),
("s.xxxxxxxxxxxxx-000-000-444", "chiquihuite (cesto de mimbre)", "chiquihuite (cesto de mimbre).png", "s."),
("adj.xxxxxxxxxxx-000-000-445", "chiquito,a",                    "chiquito,a.png",                    "adj."),
("s.xxxxxxxxxxxxx-000-000-446", "chivo,a",                       "chivo,a.png",                       "s."),
("s.xxxxxxxxxxxxx-000-000-447", "chocolate",                     "chocolate.png",                     "s."),
("s.xxxxxxxxxxxxx-000-000-448", "chompancle",                    "chompancle.png",                    "s."),
("adj.xxxxxxxxxxx-000-000-449", "chula,o",                       "chula,o.png",                       "adj."),
("v.t.pres.xxxxxx-000-000-450", "chupa",                         "chupa.png",                         "v.t.pres."),
("s.xxxxxxxxxxxxx-000-000-451", "chupamirto",                    "chupamirto.png",                    "s."),
("vt.xxxxxxxxxxxx-000-000-452", "chupar",                        "chupar.png",                        "vt."),
("adj.xxxxxxxxxxx-000-000-453", "ciego,a",                       "ciego,a.png",                       "adj."),
("adj.rev.xxxxxxx-000-000-454", "cieguito,a",                    "cieguito,a.png",                    "adj.rev."),
("s.xxxxxxxxxxxxx-000-000-455", "cielo",                         "cielo.png",                         "s."),
("s.xxxxxxxxxxxxx-000-000-456", "cienpiés",                      "cienpiés.png",                      "s."),
("s.xxxxxxxxxxxxx-000-000-457", "cien",                          "cien.png",                          "s."),
("s.xxxxxxxxxxxxx-000-000-458", "ciento diez",                   "ciento diez.png",                   "s."),
("v.t.pres.xxxxxx-000-000-459", "cierra (la boca)",              "cierra (la boca).png",              "v.t.pres."),
("compl.xxxxxxxxx-000-000-460", "cierra la casa",                "cierra la casa.png",                "compl."),
("compl.xxxxxxxxx-000-000-461", "cierra con palos",              "cierra con palos.png",              "compl."),
("adj.xxxxxxxxxxx-000-000-462", "cierto,a",                      "cierto,a.png",                      "adj."),
("s.xxxxxxxxxxxxx-000-000-463", "cigarra",                       "cigarra.png",                       "s."),
("s.xxxxxxxxxxxxx-000-000-464", "cinco",                         "cinco.png",                         "s."),
("s.xxxxxxxxxxxxx-000-000-465", "cincuenta",                     "cincuenta.png",                     "s."),
("s.xxxxxxxxxxxxx-000-000-466", "cincuenta y seis mil",          "cincuenta y seis mil.png",          "s."),
("s.xxxxxxxxxxxxx-000-000-467", "cintura",                       "cintura.png",                       "s."),
("s.xxxxxxxxxxxxx-000-000-468", "ciprés",                        "ciprés.png",                        "s."),
("v.i.xxxxxxxxxxx-000-000-469", "circular",                      "circular.png",                      "v.i."),
("s.xxxxxxxxxxxxx-000-000-470", "ciruela",                       "ciruela.png",                       "s."),
("v.t.xxxxxxxxxxx-000-000-471", "citar, mencionar",              "citar, mencionar.png",              "v.t."),
("s.xxxxxxxxxxxxx-000-000-472", "ciudad",                        "ciudad.png",                        "s."),
("s.xxxxxxxxxxxxx-000-000-473", "claridad",                      "claridad.png",                      "s.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.73
("s.xxxxxxxxxxxxxx-000-000-474", "cultivo de maíz",           "cultivo de maíz.png",           "s."),
("s.xxxxxxxxxxxxxx-000-000-475", "cultivo",                   "cultivo.png",                   "s."),
("v.t.imper.xxxxxx-000-000-476", "cúmpletelo",                "cúmpletelo.png",                "v.t.imper."),
("s.xxxxxxxxxxxxxx-000-000-477", "cuñada",                    "cuñada.png",                    "s."),
("s.xxxxxxxxxxxxxx-000-000-478", "cuñado",                    "cuñado.png",                    "s."),
("s.xxxxxxxxxxxxxx-000-000-479", "cuñado",                    "cuñado.png",                    "s."),
("s.xxxxxxxxxxxxxx-000-000-480", "cura",                      "cura.png",                      "s."),
("s.compl.xxxxxxxx-000-000-481", "curación (con hortiga)",    "curación (con hortiga).png",    "s.compl."),
("v.t.imper.xxxxxx-000-000-482", "cúrale",                    "cúrale.png",                    "v.t.imper."),
("v.t.fut.xxxxxxxx-000-000-483", "curará",                    "curará.png",                    "v.t.fut."),
("v.i.fut.xxxxxxxx-000-000-484", "curaré (me)",               "curaré (me).png",               "v.i.fut."),
("v.i.xxxxxxxxxxxx-000-000-485", "da (se) cosecha",           "da (se) cosecha.png",           "v.i."),
("adj.xxxxxxxxxxxx-000-000-486", "da comezón, pruriginoso,a", "da comezón, pruriginoso,a.png", "adj."),
("v.t.compl.xxxxxx-000-000-487", "da consejos",               "da consejos.png",               "v.t.compl."),
("v.t.pres.xxxxxxx-000-000-488", "da",                        "da.png",                        "v.t.pres."),
("v.t.imper.xxxxxx-000-000-489", "dale",                      "dale.png",                      "v.t.imper."),
("v.t.imper.compl.-000-000-490", "dale a el",                 "dale a el.png",                 "v.t.imper.compl."),
("v.t.imper.xxxxxx-000-000-491", "dale filo",                 "dale filo.png",                 "v.t.imper."),
("v.t.imper.xxxxxx-000-000-492", "dales",                     "dales.png",                     "v.t.imper."),
("v.t.compl.xxxxxx-000-000-493", "dar (de beber)",            "dar (de beber).png",            "v.t.compl."),
("v.t.compl.xxxxxx-000-000-494", "dar (de beber)",            "dar (de beber).png",            "v.t.compl."),
("v.t.compl.xxxxxx-000-000-495", "dar (respiración)",         "dar (respiración).png",         "v.t.compl."),
("v.t.xxxxxxxxxxxx-000-000-496", "dar de comer",              "dar de comer.png",              "v.t."),
("v.t.xxxxxxxxxxxx-000-000-497", "dar",                       "dar.png",                       "v.t."),
("v.t.compl.xxxxxx-000-000-498", "dará a luz",                "dará a luz.png",                "v.t.compl."),
("v.t.refl.xxxxxxx-000-000-499", "darle",                     "darle.png",                     "v.t.refl."),
("rev.xxxxxxxxxxxx-000-000-500", "darle a",                   "darle a.png",                   "rev."),
("compl.xxxxxxxxxx-000-000-501", "darse tiempo",              "darse tiempo.png",              "compl."),
("v.i.xxxxxxxxxxxx-000-000-502", "darse vueltas",             "darse vueltas.png",             "v.i."),
("v.t.imper.xxxxxx-000-000-503", "dáselos",                   "dáselos.png",                   "v.t.imper."),
("prep.compl.xxxxx-000-000-504", "de (ellos)",                "de (ellos).png",                "prep.compl."),
("compl.xxxxxxxxxx-000-000-505", "de (hombros grandes)",      "de (hombros grandes).png",      "compl."),
("v.t.imper.xxxxxx-000-000-506", "dé (la vuelta)",            "dé (la vuelta).png",            "v.t.imper."),
("compl.xxxxxxxxxx-000-000-507", "de (nada)",                 "de (nada).png",                 "compl."),
("compl.xxxxxxxxxx-000-000-508", "de (tres en tres)",         "de (tres en tres).png",         "compl."),
("compl.xxxxxxxxxx-000-000-509", "de (ustedes) adj",          "de (ustedes) adj.png",          "compl."),
("adj.xxxxxxxxxxxx-000-000-510", "de alguien",                "de alguien.png",                "adj."),
("adj.xxxxxxxxxxxx-000-000-511", "de nosotros",               "de nosotros.png",               "adj."),
("adj.xxxxxxxxxxxx-000-000-512", "de nosotros",               "de nosotros.png",               "adj."),
("d.j.compl.xxxxxx-000-000-513", "de ustedes",                "de ustedes.png",                "d.j.compl."),
("prep.xxxxxxxxxxx-000-000-514", "debajo de",                 "debajo de.png",                 "prep."),
("v.t.pres.xxxxxxx-000-000-515", "debe",                      "debe.png",                      "v.t.pres."),
("v.t.xxxxxxxxxxxx-000-000-516", "deber deuda",               "deber deuda.png",               "v.t."),
("v.t.copr.xxxxxxx-000-000-517", "debia",                     "debia.png",                     "v.t.copr.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.74
("v.t.copret.xxxxx-000-000-518", "decía",                    "decía.png",                    "v.t.copret."),
("v.t.compl.xxxxxx-000-000-519", "decir (fue a)",            "decir (fue a).png",            "v.t.compl."),
("v.t.pret.compl.x-000-000-520", "decir (le fue a)",         "decir (le fue a).png",         "v.t.pret.compl."),
("v.t.xxxxxxxxxxxx-000-000-521", "decir",                    "decir.png",                    "v.t."),
("s.adj.xxxxxxxxxx-000-000-522", "de cuclillas",             "de cuclillas.png",             "s.adj."),
("s.xxxxxxxxxxxxxx-000-000-523", "dedo (de mano)",           "dedo (de mano).png",           "s."),
("s.xxxxxxxxxxxxxx-000-000-524", "dedo del pie",             "dedo del pie.png",             "s."),
("s.xxxxxxxxxxxxxx-000-000-525", "dedo",                     "dedo.png",                     "s."),
("s.xxxxxxxxxxxxxx-000-000-526", "dedos",                    "dedos.png",                    "s."),
("adj.xxxxxxxxxxxx-000-000-527", "deforme",                  "deforme.png",                  "adj."),
("v.t.imper.xxxxxx-000-000-528", "déjalo",                   "déjalo.png",                   "v.t.imper."),
("v.t.ger.xxxxxxxx-000-000-529", "dejando",                  "dejando.png",                  "v.t.ger."),
("v.t.xxxxxxxxxxxx-000-000-530", "dejar",                    "dejar.png",                    "v.t."),
("v.i.xxxxxxxxxxxx-000-000-531", "dejar (se)",               "dejar (se).png",               "v.i."),
("v.t.fut.xxxxxxxx-000-000-532", "dejará",                   "dejará.png",                   "v.t.fut."),
("v.t.fut.xxxxxxxx-000-000-533", "dejaré (lo)",              "dejaré (lo).png",              "v.t.fut."),
("v.t.imper.rev.xx-000-000-534", "déjelo usted",             "déjelo usted.png",             "v.t.imper.rev."),
("v.t.imper.xxxxxx-000-000-535", "déjelo",                   "déjelo.png",                   "v.t.imper."),
("v.t.pret.xxxxxxx-000-000-536", "dejó (lo)",                "dejó (lo).png",                "v.t.pret."),
("v.t.v.i.pret.xxx-000-000-537", "dejó",                     "dejó.png",                     "v.t.v.i.pret."),
("v.t.imper.xxxxxx-000-000-538", "dele",                     "dele.png",                     "v.t.imper."),
("v.t.imper.xxxxxx-000-000-539", "dele a él",                "dele a él.png",                "v.t.imper."),
("v.t.imper.rev.xx-000-000-540", "dele usted",               "dele usted.png",               "v.t.imper.rev."),
("v.t.imper.rev.xx-000-000-541", "dele usted de nalgadas",   "dele usted de nalgadas.png",   "v.t.imper.rev."),
("adj.xxxxxxxxxxxx-000-000-542", "delgadito,a",              "delgadito,a.png",              "adj."),
("adj.xxxxxxxxxxxx-000-000-543", "delgado,a",                "delgado,a.png",                "adj."),
("adj.xxxxxxxxxxxx-000-000-544", "delgado,a",                "delgado,a.png",                "adj."),
("adj.xxxxxxxxxxxx-000-000-545", "demasiado",                "demasiado.png",                "adj."),
("adj.xxxxxxxxxxxx-000-000-546", "demasiado alegre",         "demasiado alegre.png",         "adj."),
("*.xxxxxxxxxxxxxx-000-000-547", "deme usted",               "deme usted.png",               "*."),
("adj.xxxxxxxxxxxx-000-000-548", "demente",                  "demente.png",                  "adj."),
("v.t.xxxxxxxxxxxx-000-000-549", "demoler",                  "demoler.png",                  "v.t."),
("v.t.imper.xxxxxx-000-000-550", "demuéstrele usted",        "demuéstrele usted.png",        "v.t.imper."),
("adv.compl.xxxxxx-000-000-551", "dentro (de la casa)",      "dentro (de la casa).png",      "adv.compl."),
("adv.xxxxxxxxxxxx-000-000-552", "dentro (del oído)",        "dentro (del oído).png",        "adv."),
("adv.compl.xxxxxx-000-000-553", "dentro de los matorrales", "dentro de los matorrales.png", "adv.compl."),
("adv.compl.xxxxxx-000-000-554", "dentro del fuego",         "dentro del fuego.png",         "adv.compl."),
("adv.compl.xxxxxx-000-000-555", "dentro del temascal",      "dentro del temascal.png",      "adv.compl."),
("adv.compl.xxxxxx-000-000-556", "dentro del agua",          "dentro del agua.png",          "adv.compl."),
("prep.xxxxxxxxxxx-000-000-557", "dentro",                   "dentro.png",                   "prep."),
("v.t.xxxxxxxxxxxx-000-000-558", "denunciar",                "denunciar.png",                "v.t."),
("s.xxxxxxxxxxxxxx-000-000-559", "depresión de tierra",      "depresión de tierra.png",      "s."),
("v.i.xxxxxxxxxxxx-000-000-560", "derretir (se)",            "derretir (se).png",            "v.i."),
("v.t.xxxxxxxxxxxx-000-000-561", "derribar",                 "derribar.png",                 "v.t.");
INSERT INTO meanings (id, meaning, image_url, category ) VALUES --pag.78
dos (veces)                        s.compl.
dos mil ochocientos                s.
dos mil ochocientos                s.
dos mil                            s.
dos milcuatrocientos               s.
dos veces                          s.compl.
doy (le)                           v.t.pres.
doy                                v.t.pres.
duele (te)                         v.i.pres.
dueño,a amo,a                      s.

duerma                             v.i.imper.
duérmase                           v.i.imper .
duérmase usted                     v.i.imper.rev.
duerme                             v.i.pres.
duerme el señor                    v.i.pres.rev.
duerme usted                       v.i.pres.rev.
duerme                             v.i.pres.rev.
duermen                            v.i.pres.
duermes                            *.
duermo                             v.i.pres.

dulce                              adj.s.
dulce golosina                     s.
durmiendo                          v.i.ger.
durmieron                          v.i.pret.
durmió                             v.i.pret.
duro,a                             adj.k.
ebrio,a borracho,a                 adj.
echa (se) de espaldas              v.i.pres.
eco (hace)                         v.i.
edificio (de la biblioteca)        s.

ejercicio                          s.
ejocote                            s.
ejote s frijol tierno              s.
el pron                            *.
el que-                            *.
el que cosecha                     *.
el se-, ellos se-                  pref.r.
ellos, ellas                       pron.
ellos, ellas (reverencial)         *.
elote                              s.
embaraza                           v.r.pres.
embarazada                         adj.
embarazo                           s.
embárrale                          v.t.imper.