INSERT INTO states ( id, name ) VALUES
  ("01AS", "Aguascalientes"),
  ("02BC", "Baja California"),
  ("03BS", "Baja California Sur"),
  ("04CC", "Campeche"),
  ("05CL", "Coahuila de Zaragoza"),
  ("06CM", "Colima"),
  ("07CS", "Chiapas"),
  ("08CH", "Chihuahua"),
  ("09DF", "Ciudad de México"),
  ("10DG", "Durango"),
  ("11GT", "Guanajuato"),
  ("12GR", "Guerrero"),
  ("13HG", "Hidalgo"),
  ("14JC", "Jalisco"),
  ("15MC", "Estado de México"),
  ("16MN", "Michoacán de Ocampo"),
  ("17MS", "Morelos"),
  ("18NT", "Nayarit"),
  ("19NL", "Nuevo León"),
  ("20OC", "Oaxaca"),
  ("21PL", "Puebla"),
  ("22QT", "Querétaro"),
  ("23QR", "Quintana Roo"),
  ("24SP", "San Luis Potosí"),
  ("25SL", "Sinaloa"),
  ("26SR", "Sonora"),
  ("27TC", "Tabasco"),
  ("28TS", "Tamaulipas"),
  ("29TL", "Tlaxcala"),
  ("30VZ", "Veracruz de Ignacio de la Llave"),
  ("31YN", "Yucatán"),
  ("32ZS", "Zacatecas"); 